export interface DTCEntry {
  code: string;
  description: string;
  severity: "critical" | "warning" | "info";
  system: "powertrain" | "body" | "chassis" | "network";
  hint?: string;
}

const DTC_DB: Record<string, Omit<DTCEntry, "code">> = {
  P0000: { description: "No Malfunction", severity: "info", system: "powertrain" },
  P0001: { description: "Fuel Volume Regulator Control Circuit/Open", severity: "warning", system: "powertrain", hint: "Check fuel pressure regulator and wiring" },
  P0002: { description: "Fuel Volume Regulator Control Circuit Range/Performance", severity: "warning", system: "powertrain" },
  P0011: { description: "Camshaft Position A Timing Over-Advanced Bank 1", severity: "warning", system: "powertrain", hint: "Low oil pressure or VVT solenoid fault" },
  P0012: { description: "Camshaft Position A Timing Over-Retarded Bank 1", severity: "warning", system: "powertrain" },
  P0013: { description: "Exhaust Camshaft Position Actuator Solenoid Bank 1", severity: "warning", system: "powertrain" },
  P0014: { description: "Camshaft Position B Timing Over-Advanced Bank 1", severity: "warning", system: "powertrain" },
  P0016: { description: "Crankshaft/Camshaft Position Correlation Bank 1 Sensor A", severity: "critical", system: "powertrain", hint: "Timing chain stretch or sensor fault" },
  P0017: { description: "Crankshaft/Camshaft Position Correlation Bank 1 Sensor B", severity: "critical", system: "powertrain" },
  P0020: { description: "Camshaft Position Actuator Circuit Bank 2", severity: "warning", system: "powertrain" },
  P0030: { description: "HO2S Heater Control Circuit Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0031: { description: "HO2S Heater Control Circuit Low Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0032: { description: "HO2S Heater Control Circuit High Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0036: { description: "HO2S Heater Control Circuit Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0037: { description: "HO2S Heater Control Circuit Low Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0038: { description: "HO2S Heater Control Circuit High Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0050: { description: "HO2S Heater Control Circuit Bank 2 Sensor 1", severity: "warning", system: "powertrain" },
  P0055: { description: "HO2S Heater Resistance Bank 1 Sensor 3", severity: "info", system: "powertrain" },
  P0068: { description: "MAP/MAF Throttle Position Correlation", severity: "warning", system: "powertrain" },
  P0069: { description: "MAP/BARO Sensor Correlation", severity: "warning", system: "powertrain" },
  P0087: { description: "Fuel Rail/System Pressure Too Low", severity: "critical", system: "powertrain", hint: "Weak fuel pump or clogged fuel filter" },
  P0088: { description: "Fuel Rail/System Pressure Too High", severity: "critical", system: "powertrain", hint: "Fuel pressure regulator failure" },
  P0089: { description: "Fuel Pressure Regulator 1 Performance", severity: "warning", system: "powertrain" },
  P0090: { description: "Fuel Pressure Regulator 1 Control Circuit", severity: "warning", system: "powertrain" },
  P0100: { description: "Mass Air Flow Circuit Malfunction", severity: "warning", system: "powertrain", hint: "Clean or replace MAF sensor" },
  P0101: { description: "Mass Air Flow Circuit Range/Performance", severity: "warning", system: "powertrain", hint: "Check for air leaks or dirty MAF" },
  P0102: { description: "Mass Air Flow Circuit Low Input", severity: "warning", system: "powertrain" },
  P0103: { description: "Mass Air Flow Circuit High Input", severity: "warning", system: "powertrain" },
  P0104: { description: "Mass Air Flow Circuit Intermittent", severity: "info", system: "powertrain" },
  P0105: { description: "Manifold Absolute Pressure Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0106: { description: "MAP Circuit Range/Performance", severity: "warning", system: "powertrain" },
  P0107: { description: "MAP Circuit Low Input", severity: "warning", system: "powertrain" },
  P0108: { description: "MAP Circuit High Input", severity: "warning", system: "powertrain" },
  P0110: { description: "Intake Air Temperature Circuit Malfunction", severity: "info", system: "powertrain" },
  P0111: { description: "IAT Circuit Range/Performance", severity: "info", system: "powertrain" },
  P0112: { description: "IAT Circuit Low Input", severity: "warning", system: "powertrain" },
  P0113: { description: "IAT Circuit High Input", severity: "warning", system: "powertrain" },
  P0115: { description: "Engine Coolant Temperature Circuit Malfunction", severity: "critical", system: "powertrain", hint: "Check coolant temp sensor and wiring" },
  P0116: { description: "ECT Circuit Range/Performance", severity: "warning", system: "powertrain" },
  P0117: { description: "ECT Circuit Low Input", severity: "warning", system: "powertrain" },
  P0118: { description: "ECT Circuit High Input", severity: "warning", system: "powertrain" },
  P0120: { description: "Throttle Position Sensor A Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0121: { description: "TPS A Circuit Range/Performance", severity: "warning", system: "powertrain" },
  P0122: { description: "TPS A Circuit Low Input", severity: "warning", system: "powertrain" },
  P0123: { description: "TPS A Circuit High Input", severity: "warning", system: "powertrain" },
  P0125: { description: "Insufficient Coolant Temp for Closed Loop Fuel Control", severity: "info", system: "powertrain" },
  P0128: { description: "Coolant Thermostat Temperature Below Regulating Temperature", severity: "warning", system: "powertrain", hint: "Thermostat stuck open" },
  P0130: { description: "O2 Sensor Circuit Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0131: { description: "O2 Sensor Circuit Low Voltage Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0132: { description: "O2 Sensor Circuit High Voltage Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0133: { description: "O2 Sensor Circuit Slow Response Bank 1 Sensor 1", severity: "warning", system: "powertrain", hint: "Oxygen sensor aging or contamination" },
  P0134: { description: "O2 Sensor Circuit No Activity Detected Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0135: { description: "O2 Sensor Heater Circuit Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0136: { description: "O2 Sensor Circuit Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0137: { description: "O2 Sensor Circuit Low Voltage Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0138: { description: "O2 Sensor Circuit High Voltage Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0139: { description: "O2 Sensor Circuit Slow Response Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0140: { description: "O2 Sensor Circuit No Activity Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0141: { description: "O2 Sensor Heater Circuit Bank 1 Sensor 2", severity: "warning", system: "powertrain" },
  P0150: { description: "O2 Sensor Circuit Bank 2 Sensor 1", severity: "warning", system: "powertrain" },
  P0155: { description: "O2 Sensor Heater Circuit Bank 2 Sensor 1", severity: "warning", system: "powertrain" },
  P0160: { description: "O2 Sensor Circuit Bank 2 Sensor 2", severity: "warning", system: "powertrain" },
  P0161: { description: "O2 Sensor Heater Circuit Bank 2 Sensor 2", severity: "warning", system: "powertrain" },
  P0170: { description: "Fuel Trim Malfunction Bank 1", severity: "warning", system: "powertrain" },
  P0171: { description: "System Too Lean Bank 1", severity: "warning", system: "powertrain", hint: "Vacuum leak, dirty MAF, or weak injectors" },
  P0172: { description: "System Too Rich Bank 1", severity: "warning", system: "powertrain", hint: "Leaking injectors or O2 sensor fault" },
  P0174: { description: "System Too Lean Bank 2", severity: "warning", system: "powertrain" },
  P0175: { description: "System Too Rich Bank 2", severity: "warning", system: "powertrain" },
  P0176: { description: "Fuel Composition Sensor Circuit", severity: "info", system: "powertrain" },
  P0180: { description: "Fuel Temperature Sensor A Circuit", severity: "info", system: "powertrain" },
  P0190: { description: "Fuel Rail Pressure Sensor A Circuit", severity: "warning", system: "powertrain" },
  P0191: { description: "Fuel Rail Pressure Sensor A Range/Performance", severity: "warning", system: "powertrain" },
  P0193: { description: "Fuel Rail Pressure Sensor A Circuit High", severity: "warning", system: "powertrain" },
  P0196: { description: "Engine Oil Temperature Sensor Range/Performance", severity: "info", system: "powertrain" },
  P0200: { description: "Injector Circuit Malfunction", severity: "critical", system: "powertrain", hint: "Check injector wiring harness" },
  P0201: { description: "Injector Circuit Malfunction - Cylinder 1", severity: "critical", system: "powertrain" },
  P0202: { description: "Injector Circuit Malfunction - Cylinder 2", severity: "critical", system: "powertrain" },
  P0203: { description: "Injector Circuit Malfunction - Cylinder 3", severity: "critical", system: "powertrain" },
  P0204: { description: "Injector Circuit Malfunction - Cylinder 4", severity: "critical", system: "powertrain" },
  P0205: { description: "Injector Circuit Malfunction - Cylinder 5", severity: "critical", system: "powertrain" },
  P0206: { description: "Injector Circuit Malfunction - Cylinder 6", severity: "critical", system: "powertrain" },
  P0207: { description: "Injector Circuit Malfunction - Cylinder 7", severity: "critical", system: "powertrain" },
  P0208: { description: "Injector Circuit Malfunction - Cylinder 8", severity: "critical", system: "powertrain" },
  P0217: { description: "Engine Over Temperature Condition", severity: "critical", system: "powertrain", hint: "Engine overheating — stop safely and check cooling system" },
  P0218: { description: "Transmission Over Temperature Condition", severity: "critical", system: "powertrain" },
  P0219: { description: "Engine Overspeed Condition", severity: "warning", system: "powertrain" },
  P0220: { description: "Throttle/Pedal Position Sensor/Switch B Circuit", severity: "warning", system: "powertrain" },
  P0221: { description: "Throttle/Pedal Position Sensor B Range/Performance", severity: "warning", system: "powertrain" },
  P0222: { description: "Throttle/Pedal Position Sensor B Circuit Low", severity: "warning", system: "powertrain" },
  P0223: { description: "Throttle/Pedal Position Sensor B Circuit High", severity: "warning", system: "powertrain" },
  P0230: { description: "Fuel Pump Primary Circuit Malfunction", severity: "critical", system: "powertrain", hint: "Check fuel pump relay and wiring" },
  P0231: { description: "Fuel Pump Secondary Circuit Low", severity: "critical", system: "powertrain" },
  P0232: { description: "Fuel Pump Secondary Circuit High", severity: "warning", system: "powertrain" },
  P0234: { description: "Turbocharger/Supercharger Overboost", severity: "critical", system: "powertrain", hint: "Check wastegate or boost control solenoid" },
  P0235: { description: "Turbocharger Boost Sensor A Circuit", severity: "warning", system: "powertrain" },
  P0236: { description: "Turbocharger Boost Sensor A Range/Performance", severity: "warning", system: "powertrain" },
  P0237: { description: "Turbocharger Boost Sensor A Circuit Low", severity: "warning", system: "powertrain" },
  P0238: { description: "Turbocharger Boost Sensor A Circuit High", severity: "warning", system: "powertrain" },
  P0243: { description: "Turbocharger Wastegate Solenoid A", severity: "warning", system: "powertrain" },
  P0245: { description: "Turbocharger Wastegate Solenoid A Low", severity: "warning", system: "powertrain" },
  P0246: { description: "Turbocharger Wastegate Solenoid A High", severity: "warning", system: "powertrain" },
  P0261: { description: "Cylinder 1 Injector Circuit Low", severity: "critical", system: "powertrain" },
  P0262: { description: "Cylinder 1 Injector Circuit High", severity: "critical", system: "powertrain" },
  P0263: { description: "Cylinder 1 Contribution/Balance Fault", severity: "warning", system: "powertrain" },
  P0264: { description: "Cylinder 2 Injector Circuit Low", severity: "critical", system: "powertrain" },
  P0265: { description: "Cylinder 2 Injector Circuit High", severity: "critical", system: "powertrain" },
  P0300: { description: "Random/Multiple Cylinder Misfire Detected", severity: "critical", system: "powertrain", hint: "Check spark plugs, coils, and injectors" },
  P0301: { description: "Cylinder 1 Misfire Detected", severity: "critical", system: "powertrain", hint: "Check spark plug and coil for cylinder 1" },
  P0302: { description: "Cylinder 2 Misfire Detected", severity: "critical", system: "powertrain" },
  P0303: { description: "Cylinder 3 Misfire Detected", severity: "critical", system: "powertrain" },
  P0304: { description: "Cylinder 4 Misfire Detected", severity: "critical", system: "powertrain" },
  P0305: { description: "Cylinder 5 Misfire Detected", severity: "critical", system: "powertrain" },
  P0306: { description: "Cylinder 6 Misfire Detected", severity: "critical", system: "powertrain" },
  P0307: { description: "Cylinder 7 Misfire Detected", severity: "critical", system: "powertrain" },
  P0308: { description: "Cylinder 8 Misfire Detected", severity: "critical", system: "powertrain" },
  P0320: { description: "Ignition/Distributor Engine Speed Input Circuit Malfunction", severity: "critical", system: "powertrain" },
  P0325: { description: "Knock Sensor 1 Circuit Bank 1", severity: "warning", system: "powertrain", hint: "Check knock sensor connector and wiring" },
  P0326: { description: "Knock Sensor 1 Range/Performance Bank 1", severity: "warning", system: "powertrain" },
  P0327: { description: "Knock Sensor 1 Circuit Low Bank 1", severity: "warning", system: "powertrain" },
  P0328: { description: "Knock Sensor 1 Circuit High Bank 1", severity: "warning", system: "powertrain" },
  P0330: { description: "Knock Sensor 2 Circuit Bank 2", severity: "warning", system: "powertrain" },
  P0335: { description: "Crankshaft Position Sensor A Circuit Malfunction", severity: "critical", system: "powertrain", hint: "No-start condition possible; check CKP sensor" },
  P0336: { description: "CKP Sensor A Circuit Range/Performance", severity: "critical", system: "powertrain" },
  P0337: { description: "CKP Sensor A Circuit Low Input", severity: "critical", system: "powertrain" },
  P0338: { description: "CKP Sensor A Circuit High Input", severity: "critical", system: "powertrain" },
  P0339: { description: "CKP Sensor A Circuit Intermittent", severity: "warning", system: "powertrain" },
  P0340: { description: "Camshaft Position Sensor A Circuit Bank 1", severity: "critical", system: "powertrain" },
  P0341: { description: "CMP Sensor A Circuit Range/Performance Bank 1", severity: "warning", system: "powertrain" },
  P0345: { description: "CMP Sensor A Circuit Bank 2", severity: "critical", system: "powertrain" },
  P0380: { description: "Glow Plug/Heater Circuit A", severity: "warning", system: "powertrain" },
  P0400: { description: "Exhaust Gas Recirculation Flow Malfunction", severity: "warning", system: "powertrain" },
  P0401: { description: "EGR Flow Insufficient Detected", severity: "warning", system: "powertrain", hint: "Clean or replace EGR valve" },
  P0402: { description: "EGR Flow Excessive Detected", severity: "warning", system: "powertrain" },
  P0403: { description: "EGR Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0404: { description: "EGR Circuit Range/Performance", severity: "warning", system: "powertrain" },
  P0405: { description: "EGR Sensor A Circuit Low", severity: "warning", system: "powertrain" },
  P0406: { description: "EGR Sensor A Circuit High", severity: "warning", system: "powertrain" },
  P0410: { description: "Secondary Air Injection System Malfunction", severity: "warning", system: "powertrain" },
  P0411: { description: "Secondary Air Injection Incorrect Flow Detected", severity: "warning", system: "powertrain" },
  P0420: { description: "Catalyst System Efficiency Below Threshold Bank 1", severity: "warning", system: "powertrain", hint: "Catalytic converter may need replacement" },
  P0421: { description: "Warm Up Catalyst Efficiency Below Threshold Bank 1", severity: "warning", system: "powertrain" },
  P0422: { description: "Main Catalyst Efficiency Below Threshold Bank 1", severity: "warning", system: "powertrain" },
  P0430: { description: "Catalyst System Efficiency Below Threshold Bank 2", severity: "warning", system: "powertrain" },
  P0440: { description: "Evaporative Emission Control System Malfunction", severity: "warning", system: "powertrain" },
  P0441: { description: "EVAP Emission Control System Incorrect Purge Flow", severity: "warning", system: "powertrain" },
  P0442: { description: "EVAP Emission Control System Leak Detected (small leak)", severity: "info", system: "powertrain", hint: "Check gas cap seal first" },
  P0443: { description: "EVAP Emission Control System Purge Control Valve Circuit", severity: "warning", system: "powertrain" },
  P0446: { description: "EVAP Emission Control System Vent Control Circuit", severity: "warning", system: "powertrain" },
  P0448: { description: "EVAP System Vent Control Circuit High", severity: "warning", system: "powertrain" },
  P0449: { description: "EVAP System Vent Valve/Solenoid Circuit", severity: "warning", system: "powertrain" },
  P0451: { description: "EVAP Emission Control System Pressure Sensor Range/Performance", severity: "info", system: "powertrain" },
  P0452: { description: "EVAP Emission Control System Pressure Sensor Low", severity: "info", system: "powertrain" },
  P0453: { description: "EVAP Emission Control System Pressure Sensor High", severity: "info", system: "powertrain" },
  P0455: { description: "EVAP Emission Control System Leak Detected (large leak)", severity: "warning", system: "powertrain", hint: "Check gas cap and EVAP hoses" },
  P0456: { description: "EVAP Emission Control System Leak Detected (very small leak)", severity: "info", system: "powertrain" },
  P0460: { description: "Fuel Level Sensor Circuit Malfunction", severity: "info", system: "powertrain" },
  P0461: { description: "Fuel Level Sensor Range/Performance", severity: "info", system: "powertrain" },
  P0462: { description: "Fuel Level Sensor Circuit Low", severity: "info", system: "powertrain" },
  P0463: { description: "Fuel Level Sensor Circuit High", severity: "info", system: "powertrain" },
  P0480: { description: "Cooling Fan 1 Control Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0481: { description: "Cooling Fan 2 Control Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0482: { description: "Cooling Fan 3 Control Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0483: { description: "Cooling Fan Rationality Check", severity: "warning", system: "powertrain" },
  P0484: { description: "Cooling Fan Circuit Over Current", severity: "warning", system: "powertrain" },
  P0485: { description: "Cooling Fan Power/Ground Circuit", severity: "warning", system: "powertrain" },
  P0500: { description: "Vehicle Speed Sensor Malfunction", severity: "warning", system: "powertrain" },
  P0501: { description: "VSS Range/Performance", severity: "warning", system: "powertrain" },
  P0502: { description: "VSS Input Circuit Low", severity: "warning", system: "powertrain" },
  P0503: { description: "VSS Input Circuit High/Erratic", severity: "warning", system: "powertrain" },
  P0505: { description: "Idle Air Control System Malfunction", severity: "warning", system: "powertrain", hint: "Clean IAC valve or throttle body" },
  P0506: { description: "Idle Control System RPM Lower Than Expected", severity: "warning", system: "powertrain" },
  P0507: { description: "Idle Control System RPM Higher Than Expected", severity: "warning", system: "powertrain" },
  P0510: { description: "Closed Throttle Position Switch Malfunction", severity: "warning", system: "powertrain" },
  P0520: { description: "Engine Oil Pressure Sensor/Switch Circuit Malfunction", severity: "critical", system: "powertrain", hint: "Check oil level and pressure sensor" },
  P0521: { description: "Engine Oil Pressure Sensor Range/Performance", severity: "critical", system: "powertrain" },
  P0522: { description: "Engine Oil Pressure Sensor Circuit Low", severity: "critical", system: "powertrain" },
  P0523: { description: "Engine Oil Pressure Sensor Circuit High", severity: "warning", system: "powertrain" },
  P0524: { description: "Engine Oil Pressure Too Low", severity: "critical", system: "powertrain", hint: "Stop engine immediately, check oil level" },
  P0530: { description: "A/C Refrigerant Pressure Sensor Circuit", severity: "info", system: "powertrain" },
  P0532: { description: "A/C Refrigerant Pressure Sensor Circuit Low", severity: "info", system: "powertrain" },
  P0533: { description: "A/C Refrigerant Pressure Sensor Circuit High", severity: "warning", system: "powertrain" },
  P0534: { description: "Air Conditioner Refrigerant Charge Loss", severity: "warning", system: "powertrain" },
  P0544: { description: "Exhaust Gas Temperature Sensor Circuit Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0545: { description: "EGT Sensor Circuit Low Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0546: { description: "EGT Sensor Circuit High Bank 1 Sensor 1", severity: "warning", system: "powertrain" },
  P0600: { description: "Serial Communication Link Malfunction", severity: "critical", system: "network" },
  P0601: { description: "Internal Control Module Memory Check Sum Error", severity: "critical", system: "powertrain" },
  P0602: { description: "Control Module Programming Error", severity: "critical", system: "powertrain" },
  P0603: { description: "Internal Control Module KAM Error", severity: "critical", system: "powertrain" },
  P0604: { description: "Internal Control Module RAM Error", severity: "critical", system: "powertrain" },
  P0605: { description: "Internal Control Module ROM Error", severity: "critical", system: "powertrain" },
  P0606: { description: "PCM Processor Fault", severity: "critical", system: "powertrain" },
  P0607: { description: "Control Module Performance", severity: "critical", system: "powertrain" },
  P0608: { description: "Control Module VSS Output A", severity: "warning", system: "powertrain" },
  P0615: { description: "Starter Relay Circuit", severity: "warning", system: "powertrain" },
  P0616: { description: "Starter Relay Circuit Low", severity: "warning", system: "powertrain" },
  P0617: { description: "Starter Relay Circuit High", severity: "warning", system: "powertrain" },
  P0620: { description: "Generator Control Circuit", severity: "warning", system: "powertrain" },
  P0621: { description: "Generator Lamp L Control Circuit", severity: "info", system: "powertrain" },
  P0622: { description: "Generator Field F Control Circuit", severity: "warning", system: "powertrain" },
  P0625: { description: "Generator Field Terminal Circuit Low", severity: "warning", system: "powertrain" },
  P0626: { description: "Generator Field Terminal Circuit High", severity: "warning", system: "powertrain" },
  P0627: { description: "Fuel Pump A Control Circuit Open", severity: "critical", system: "powertrain" },
  P0628: { description: "Fuel Pump A Control Circuit Low", severity: "critical", system: "powertrain" },
  P0629: { description: "Fuel Pump A Control Circuit High", severity: "warning", system: "powertrain" },
  P0630: { description: "VIN Not Programmed or Incompatible ECM/PCM", severity: "warning", system: "powertrain" },
  P0700: { description: "Transmission Control System Malfunction", severity: "warning", system: "powertrain", hint: "Check transmission module and fluid" },
  P0701: { description: "TCM Range/Performance", severity: "warning", system: "powertrain" },
  P0702: { description: "TCM Electrical", severity: "critical", system: "powertrain" },
  P0703: { description: "Torque Converter/Brake Switch B Circuit", severity: "warning", system: "powertrain" },
  P0704: { description: "Clutch Switch Input Circuit Malfunction", severity: "info", system: "powertrain" },
  P0705: { description: "TR Sensor Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0706: { description: "TR Sensor Range/Performance", severity: "warning", system: "powertrain" },
  P0710: { description: "Transmission Fluid Temperature Sensor Circuit", severity: "warning", system: "powertrain" },
  P0711: { description: "TFT Sensor Range/Performance", severity: "warning", system: "powertrain" },
  P0712: { description: "TFT Sensor Circuit Low Input", severity: "warning", system: "powertrain" },
  P0713: { description: "TFT Sensor Circuit High Input", severity: "warning", system: "powertrain" },
  P0714: { description: "TFT Sensor Circuit Intermittent", severity: "info", system: "powertrain" },
  P0715: { description: "Input/Turbine Speed Sensor Circuit", severity: "warning", system: "powertrain" },
  P0716: { description: "Input/Turbine Speed Sensor Range/Performance", severity: "warning", system: "powertrain" },
  P0717: { description: "Input/Turbine Speed Sensor No Signal", severity: "warning", system: "powertrain" },
  P0720: { description: "Output Speed Sensor Circuit", severity: "warning", system: "powertrain" },
  P0730: { description: "Incorrect Gear Ratio", severity: "critical", system: "powertrain" },
  P0731: { description: "Gear 1 Incorrect Ratio", severity: "critical", system: "powertrain" },
  P0732: { description: "Gear 2 Incorrect Ratio", severity: "critical", system: "powertrain" },
  P0733: { description: "Gear 3 Incorrect Ratio", severity: "critical", system: "powertrain" },
  P0734: { description: "Gear 4 Incorrect Ratio", severity: "critical", system: "powertrain" },
  P0735: { description: "Gear 5 Incorrect Ratio", severity: "critical", system: "powertrain" },
  P0740: { description: "Torque Converter Clutch Circuit Malfunction", severity: "warning", system: "powertrain" },
  P0741: { description: "TCC Circuit Performance or Stuck Off", severity: "warning", system: "powertrain" },
  P0748: { description: "Pressure Control Solenoid A Electrical", severity: "warning", system: "powertrain" },
  P0750: { description: "Shift Solenoid A Malfunction", severity: "warning", system: "powertrain" },
  P0755: { description: "Shift Solenoid B Malfunction", severity: "warning", system: "powertrain" },
  P0760: { description: "Shift Solenoid C Malfunction", severity: "warning", system: "powertrain" },
  P0765: { description: "Shift Solenoid D Malfunction", severity: "warning", system: "powertrain" },
  P0770: { description: "Shift Solenoid E Malfunction", severity: "warning", system: "powertrain" },
  P0780: { description: "Shift Malfunction", severity: "warning", system: "powertrain" },
  P0840: { description: "Transmission Fluid Pressure Sensor Circuit", severity: "warning", system: "powertrain" },
  P0841: { description: "TFP Sensor Range/Performance", severity: "warning", system: "powertrain" },
  P0850: { description: "Park/Neutral Position Switch Circuit", severity: "info", system: "powertrain" },
  P0868: { description: "Transmission Fluid Pressure Low", severity: "warning", system: "powertrain" },
  P0869: { description: "Transmission Fluid Pressure High", severity: "warning", system: "powertrain" },
  P0880: { description: "TCM Power Input Signal", severity: "critical", system: "powertrain" },
  P0882: { description: "TCM Power Input Signal Low", severity: "critical", system: "powertrain" },
  P0883: { description: "TCM Power Input Signal High", severity: "warning", system: "powertrain" },
  P0900: { description: "Clutch Actuator Circuit Open", severity: "warning", system: "powertrain" },
  P0901: { description: "Clutch Actuator Circuit Range/Performance", severity: "warning", system: "powertrain" },
  P0950: { description: "Shift Control System", severity: "warning", system: "powertrain" },
  B0001: { description: "Driver Frontal Stage 1 Deployment Control", severity: "critical", system: "body" },
  B0002: { description: "Driver Frontal Stage 2 Deployment Control", severity: "critical", system: "body" },
  B0004: { description: "Passenger Frontal Stage 1 Deployment Control", severity: "critical", system: "body" },
  B0005: { description: "Passenger Frontal Stage 2 Deployment Control", severity: "critical", system: "body" },
  B0006: { description: "Frontal Sensor (Left/Center) Circuit", severity: "critical", system: "body" },
  B0008: { description: "Side Crash Sensor LF Circuit", severity: "critical", system: "body" },
  B0009: { description: "Side Crash Sensor RF Circuit", severity: "critical", system: "body" },
  B0010: { description: "Side Crash Sensor LR Circuit", severity: "warning", system: "body" },
  B0011: { description: "Side Crash Sensor RR Circuit", severity: "warning", system: "body" },
  B0051: { description: "Air Bag Deployment Loop Resistance Low", severity: "critical", system: "body" },
  B0053: { description: "Air Bag Deployment Loop Resistance High", severity: "critical", system: "body" },
  B0055: { description: "Air Bag Deployment Loop Short to Ground", severity: "critical", system: "body" },
  B0056: { description: "Air Bag Deployment Loop Short to Voltage", severity: "critical", system: "body" },
  B0100: { description: "Air Bag Indicator Circuit Open", severity: "warning", system: "body" },
  B0101: { description: "Air Bag Indicator Circuit Short to Ground", severity: "warning", system: "body" },
  B1000: { description: "Electronic Control Unit Hardware", severity: "critical", system: "body" },
  B1001: { description: "Option Configuration Error", severity: "warning", system: "body" },
  B1004: { description: "Option Configuration Error - Class 2 Bus", severity: "warning", system: "body" },
  B1213: { description: "Theft Deterrent System Tamper Alarm", severity: "warning", system: "body" },
  B1352: { description: "Ignition Key-In Circuit Open", severity: "info", system: "body" },
  B1600: { description: "PATS Ignition Key Not Programmed", severity: "warning", system: "body" },
  C0000: { description: "No DTC's Current", severity: "info", system: "chassis" },
  C0001: { description: "RR Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0002: { description: "RF Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0003: { description: "LR Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0004: { description: "LF Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0035: { description: "Left Front Wheel Speed Sensor Circuit", severity: "warning", system: "chassis", hint: "Check ABS sensor and tone ring" },
  C0040: { description: "Right Front Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0045: { description: "Left Rear Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0050: { description: "Right Rear Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0110: { description: "Pump Motor Circuit Malfunction", severity: "warning", system: "chassis" },
  C0121: { description: "ABS Valve Relay Circuit Malfunction", severity: "warning", system: "chassis" },
  C0131: { description: "ABS/TCS/ESC Pressure Circuit Malfunction", severity: "warning", system: "chassis" },
  C0161: { description: "ABS/TCS Brake Switch Circuit Malfunction", severity: "warning", system: "chassis" },
  C0186: { description: "Lateral Accelerometer Circuit Malfunction", severity: "info", system: "chassis" },
  C0196: { description: "Yaw Rate Sensor Circuit Malfunction", severity: "warning", system: "chassis" },
  C0200: { description: "Right Front Wheel Speed Sensor Circuit", severity: "warning", system: "chassis" },
  C0265: { description: "Electronic Brake Control Module Relay Circuit", severity: "critical", system: "chassis" },
  C0266: { description: "Electronic Brake Control Module Relay Circuit Open", severity: "critical", system: "chassis" },
  C0267: { description: "Pump Motor Circuit Open/Short to Ground", severity: "warning", system: "chassis" },
  C0268: { description: "Pump Motor Circuit Short to Voltage", severity: "warning", system: "chassis" },
  C0271: { description: "EBCM Reset Circuit Malfunction", severity: "critical", system: "chassis" },
  C0281: { description: "Drive Wheels Speed Sensor Circuit", severity: "warning", system: "chassis" },
  U0001: { description: "High Speed CAN Communication Bus", severity: "critical", system: "network" },
  U0002: { description: "High Speed CAN Communication Bus Performance", severity: "critical", system: "network" },
  U0010: { description: "Medium Speed CAN Communication Bus", severity: "warning", system: "network" },
  U0020: { description: "Low Speed CAN Communication Bus", severity: "warning", system: "network" },
  U0028: { description: "Vehicle Communication Bus A", severity: "warning", system: "network" },
  U0029: { description: "Vehicle Communication Bus A Performance", severity: "warning", system: "network" },
  U0073: { description: "Control Module Communication Bus Off", severity: "critical", system: "network" },
  U0100: { description: "Lost Communication With ECM/PCM", severity: "critical", system: "network", hint: "Check CAN bus wiring and ECM power" },
  U0101: { description: "Lost Communication With TCM", severity: "critical", system: "network" },
  U0103: { description: "Lost Communication With Gear Shift Module", severity: "warning", system: "network" },
  U0104: { description: "Lost Communication With Cruise Control Module", severity: "warning", system: "network" },
  U0106: { description: "Lost Communication With Glow Plug Module", severity: "warning", system: "network" },
  U0109: { description: "Lost Communication With Fuel Pump Control Module", severity: "critical", system: "network" },
  U0110: { description: "Lost Communication With Drive Motor Control Module", severity: "critical", system: "network" },
  U0111: { description: "Lost Communication With Battery Energy Control Module", severity: "critical", system: "network" },
  U0114: { description: "Lost Communication With Four-Wheel Drive Clutch Control Module", severity: "warning", system: "network" },
  U0121: { description: "Lost Communication With ABS Control Module", severity: "critical", system: "network" },
  U0122: { description: "Lost Communication With Vehicle Stability Control Module", severity: "critical", system: "network" },
  U0123: { description: "Lost Communication With Yaw Rate Sensor Module", severity: "warning", system: "network" },
  U0126: { description: "Lost Communication With Steering Angle Sensor Module", severity: "warning", system: "network" },
  U0128: { description: "Lost Communication With Park Brake Control Module", severity: "warning", system: "network" },
  U0129: { description: "Lost Communication With Brake System Control Module", severity: "critical", system: "network" },
  U0131: { description: "Lost Communication With Power Steering Control Module", severity: "warning", system: "network" },
  U0140: { description: "Lost Communication With Body Control Module", severity: "warning", system: "network" },
  U0141: { description: "Lost Communication With Body Control Module A", severity: "warning", system: "network" },
  U0146: { description: "Lost Communication With Gateway Module", severity: "warning", system: "network" },
  U0151: { description: "Lost Communication With Restraints Control Module", severity: "critical", system: "network" },
  U0155: { description: "Lost Communication With Instrument Panel Control Module", severity: "warning", system: "network" },
  U0159: { description: "Lost Communication With Parking Assist Control Module", severity: "info", system: "network" },
  U0164: { description: "Lost Communication With HVAC Control Module", severity: "info", system: "network" },
  U0167: { description: "Lost Communication With Vehicle Immobilizer Control Module", severity: "warning", system: "network" },
  U0168: { description: "Lost Communication With Vehicle Security Control Module", severity: "warning", system: "network" },
  U0184: { description: "Lost Communication With Radio", severity: "info", system: "network" },
  U0196: { description: "Lost Communication With Radio Rear Control Module", severity: "info", system: "network" },
  U0214: { description: "Lost Communication With Remote Keyless Entry Module", severity: "info", system: "network" },
  U0301: { description: "Software Incompatibility With ECM/PCM", severity: "critical", system: "network" },
  U0401: { description: "Invalid Data Received From ECM/PCM", severity: "critical", system: "network" },
  U0402: { description: "Invalid Data Received From TCM", severity: "critical", system: "network" },
  U0411: { description: "Invalid Data Received From FICM", severity: "warning", system: "network" },
  U0422: { description: "Invalid Data Received From Body Control Module", severity: "warning", system: "network" },
  U0424: { description: "Invalid Data Received From HVAC Control Module", severity: "info", system: "network" },
  U0431: { description: "Invalid Data Received From Instrument Panel Control Module", severity: "info", system: "network" },
  U0433: { description: "Invalid Data Received From ABS Control Module", severity: "critical", system: "network" },
  U2100: { description: "Initial Configuration Not Complete", severity: "warning", system: "network" },
  U2101: { description: "Control Module Configuration Incompatible", severity: "warning", system: "network" },
  U2104: { description: "Control Module Self Test Active", severity: "info", system: "network" },
};

export function lookupDTC(code: string): DTCEntry {
  const upper = code.toUpperCase().trim();
  const entry = DTC_DB[upper];
  if (entry) {
    return { code: upper, ...entry };
  }
  const firstChar = upper[0];
  let system: DTCEntry["system"] = "powertrain";
  if (firstChar === "B") system = "body";
  else if (firstChar === "C") system = "chassis";
  else if (firstChar === "U") system = "network";
  return {
    code: upper,
    description: `Unknown DTC ${upper}`,
    severity: "warning",
    system,
  };
}

export function parseDTCResponse(response: string): string[] {
  const codes: string[] = [];
  try {
    const clean = response.replace(/\s/g, "").toUpperCase();
    let idx = clean.indexOf("43");
    if (idx === -1) return codes;
    idx += 2;
    const count = clean.length - idx;
    for (let i = 0; i < count - 3; i += 4) {
      const byteA = clean.substring(idx + i, idx + i + 2);
      const byteB = clean.substring(idx + i + 2, idx + i + 4);
      if (byteA === "00" && byteB === "00") continue;
      const a = parseInt(byteA, 16);
      const b = parseInt(byteB, 16);
      if (isNaN(a) || isNaN(b)) continue;
      const typeNibble = (a >> 6) & 0x03;
      const prefix = ["P", "C", "B", "U"][typeNibble];
      const firstDigit = ((a >> 4) & 0x03).toString();
      const secondDigit = (a & 0x0f).toString(16).toUpperCase();
      const thirdDigit = ((b >> 4) & 0x0f).toString(16).toUpperCase();
      const fourthDigit = (b & 0x0f).toString(16).toUpperCase();
      const codeStr = `${prefix}${firstDigit}${secondDigit}${thirdDigit}${fourthDigit}`;
      codes.push(codeStr);
    }
  } catch {
    // ignore
  }
  return codes;
}
