export interface OBDCommandStep {
  cmd: string;
  desc: string;
  timeoutMs?: number;
  expectOk?: boolean;
}

export interface ServiceReset {
  id: string;
  name: string;
  description: string;
  category: string;
  warning?: string;
  steps?: string[];
  requiresEngineOff?: boolean;
  requiresEngineOn?: boolean;
  icon: string;
  dangerous: boolean;
  obdCommands: OBDCommandStep[];
}

export const SERVICE_CATEGORIES = [
  "Engine",
  "Transmission",
  "Brakes",
  "Steering",
  "Tires",
  "Body",
  "HVAC",
  "Battery",
  "Keys & Security",
];

const ECM = "ATSH 7E0";
const TCM = "ATSH 7E1";
const ABS = "ATSH 760";
const BCM = "ATSH 7B0";
const HVAC = "ATSH 733";
const EPS = "ATSH 730";

const commonStart = (header: string): OBDCommandStep[] => [
  { cmd: "ATSP0", desc: "Auto-detect vehicle protocol", timeoutMs: 5000, expectOk: true },
  { cmd: "ATH1", desc: "Enable headers for module responses", timeoutMs: 1000, expectOk: true },
  { cmd: header, desc: "Select target module", timeoutMs: 1000, expectOk: true },
  { cmd: "1003", desc: "Open extended diagnostic session", timeoutMs: 3000, expectOk: true },
  { cmd: "3E00", desc: "Keep diagnostic session alive", timeoutMs: 1000, expectOk: false },
];

const finish: OBDCommandStep[] = [
  { cmd: "3E00", desc: "Keep session alive while module stores changes", timeoutMs: 1000, expectOk: false },
  { cmd: "1001", desc: "Return module to default diagnostic session", timeoutMs: 1000, expectOk: false },
  { cmd: ECM, desc: "Return header to ECM", timeoutMs: 1000, expectOk: false },
];

const routine = (id: string, desc: string): OBDCommandStep => ({
  cmd: `3101${id}`,
  desc,
  timeoutMs: 7000,
  expectOk: true,
});

const writeData = (idAndData: string, desc: string): OBDCommandStep => ({
  cmd: `2E${idAndData}`,
  desc,
  timeoutMs: 5000,
  expectOk: true,
});

export const SERVICE_RESETS: ServiceReset[] = [
  {
    id: "oil_reset",
    name: "Oil Life Reset",
    description: "Reset engine oil life monitor after oil service. Uses an OEM-style routine when the ECM/BCM supports it.",
    category: "Engine",
    icon: "droplet",
    dangerous: false,
    requiresEngineOff: true,
    obdCommands: [...commonStart(ECM), routine("FF00", "Run oil-life/service interval reset routine"), ...finish],
    steps: ["Ignition ON, engine OFF", "Run reset", "Cycle ignition OFF then ON", "Verify oil life/service message cleared"],
  },
  {
    id: "throttle_relearn",
    name: "Throttle Body Relearn",
    description: "Request throttle/idle actuator learn after throttle body cleaning or replacement.",
    category: "Engine",
    icon: "activity",
    dangerous: false,
    requiresEngineOff: true,
    obdCommands: [...commonStart(ECM), routine("FF01", "Run throttle position learn routine"), ...finish],
    steps: ["Ignition ON, engine OFF", "Do not touch accelerator", "Run relearn", "Start and idle until stable"],
  },
  {
    id: "idle_relearn",
    name: "Idle Speed Relearn",
    description: "Clear idle adaptive values and request idle relearn.",
    category: "Engine",
    icon: "sliders",
    dangerous: false,
    requiresEngineOn: true,
    obdCommands: [...commonStart(ECM), routine("FF02", "Run idle air/adaptive relearn routine"), ...finish],
    steps: ["Engine warm", "A/C and accessories OFF", "Run reset", "Let engine idle several minutes"],
  },
  {
    id: "evap_reset",
    name: "EVAP Monitor Reset",
    description: "Clear emissions readiness by clearing DTC memory; monitor must rerun during a drive cycle.",
    category: "Engine",
    icon: "cloud",
    dangerous: false,
    obdCommands: [{ cmd: "04", desc: "Clear emissions DTCs/readiness monitors", timeoutMs: 7000, expectOk: true }],
    steps: ["Repair EVAP faults first", "Run clear", "Complete the required drive cycle"],
  },
  {
    id: "fuel_trim_reset",
    name: "Fuel Trim / Injector Adapt Reset",
    description: "Clear fuel trim adaptive memory where supported by the ECM.",
    category: "Engine",
    icon: "zap",
    dangerous: false,
    obdCommands: [...commonStart(ECM), routine("FF03", "Run fuel trim adaptive reset routine"), ...finish],
    steps: ["Engine warm", "No active fuel system faults", "Run reset", "Drive normally while trims relearn"],
  },
  {
    id: "maf_reset",
    name: "MAF Adaptation Reset",
    description: "Clear MAF airflow adaptive values after sensor cleaning or replacement.",
    category: "Engine",
    icon: "wind",
    dangerous: false,
    obdCommands: [...commonStart(ECM), routine("FF04", "Run MAF adaptive reset routine"), ...finish],
    steps: ["Install/clean MAF", "Run reset", "Idle two minutes", "Light drive cycle"],
  },
  {
    id: "trans_adaptive",
    name: "Transmission Adaptive Reset",
    description: "Clear learned shift adaptives where supported by the TCM.",
    category: "Transmission",
    icon: "git-branch",
    dangerous: true,
    warning: "Shifts may feel harsh until relearn completes. Drive gently after reset.",
    obdCommands: [...commonStart(TCM), routine("FF10", "Run TCM shift adaptive reset routine"), ...finish],
    steps: ["Transmission at operating temperature", "Vehicle stopped", "Run reset", "Perform gentle relearn drive"],
  },
  {
    id: "tcc_reset",
    name: "TCC Adaptation Reset",
    description: "Reset torque converter clutch slip/adaptive values where supported.",
    category: "Transmission",
    icon: "settings",
    dangerous: false,
    obdCommands: [...commonStart(TCM), routine("FF11", "Run TCC adaptive reset routine"), ...finish],
    steps: ["Vehicle stopped", "Run reset", "Drive at steady speeds so TCC can relearn"],
  },
  {
    id: "epb_retract",
    name: "EPB Retract Service Mode",
    description: "Command electronic parking brake service/retract mode where supported by ABS/EPB module.",
    category: "Brakes",
    icon: "unlock",
    dangerous: true,
    warning: "Chock wheels first. Vehicle can roll while EPB is released.",
    requiresEngineOff: true,
    obdCommands: [...commonStart(ABS), routine("FF20", "Run EPB retract/service mode routine"), ...finish],
    steps: ["Flat surface", "Chock wheels", "Ignition ON", "Run retract", "Replace pads"],
  },
  {
    id: "epb_apply",
    name: "EPB Apply / Exit Service Mode",
    description: "Seat electronic parking brake after service where supported.",
    category: "Brakes",
    icon: "lock",
    dangerous: true,
    obdCommands: [...commonStart(ABS), routine("FF21", "Run EPB apply/exit service mode routine"), ...finish],
    steps: ["Pads installed", "Ignition ON", "Run apply", "Verify brake pedal and EPB operation"],
  },
  {
    id: "abs_bleed",
    name: "ABS Pump Bleeding",
    description: "Cycle ABS hydraulic bleed routine where supported.",
    category: "Brakes",
    icon: "droplet",
    dangerous: true,
    warning: "Only run during proper brake bleeding with fluid maintained. Do not run system dry.",
    obdCommands: [...commonStart(ABS), routine("FF22", "Run ABS automated bleed routine"), ...finish],
    steps: ["Fill brake fluid", "Attach bleed equipment", "Run routine", "Follow wheel sequence"],
  },
  {
    id: "brake_wear_reset",
    name: "Brake Wear Indicator Reset",
    description: "Reset brake pad wear counter/sensor warning where supported.",
    category: "Brakes",
    icon: "disc",
    dangerous: false,
    obdCommands: [...commonStart(ABS), routine("FF23", "Run brake wear reset routine"), ...finish],
    steps: ["Install pads/sensors", "Run reset", "Verify warning cleared"],
  },
  {
    id: "steering_angle",
    name: "Steering Angle Calibration",
    description: "Calibrate steering angle sensor after alignment or steering service.",
    category: "Steering",
    icon: "navigation",
    dangerous: false,
    requiresEngineOn: true,
    obdCommands: [...commonStart(EPS), routine("FF30", "Run steering angle zero-point calibration"), ...finish],
    steps: ["Wheels straight", "Flat level surface", "Run calibration", "Drive slowly straight ahead"],
  },
  {
    id: "eps_reset",
    name: "EPS Torque Sensor Reset",
    description: "Reset EPS torque sensor zero-point where supported.",
    category: "Steering",
    icon: "refresh-cw",
    dangerous: false,
    obdCommands: [...commonStart(EPS), routine("FF31", "Run EPS torque zero-point reset"), ...finish],
    steps: ["Steering centered", "Hands off wheel", "Run reset", "Verify assist works normally"],
  },
  {
    id: "tpms_relearn",
    name: "TPMS Sensor Relearn",
    description: "Request TPMS learn mode where supported by BCM/TPMS module.",
    category: "Tires",
    icon: "circle",
    dangerous: false,
    obdCommands: [...commonStart(BCM), routine("FF40", "Enter TPMS sensor learn mode"), ...finish],
    steps: ["Set tire pressures", "Run learn mode", "Trigger sensors FL/FR/RR/RL", "Verify IDs learned"],
  },
  {
    id: "tpms_pressure_reset",
    name: "TPMS Pressure Baseline",
    description: "Store current tire pressure baseline where supported.",
    category: "Tires",
    icon: "trending-up",
    dangerous: false,
    obdCommands: [...commonStart(BCM), routine("FF41", "Store TPMS pressure baseline routine"), ...finish],
    steps: ["Inflate all tires to placard", "Run reset", "Drive until warning clears"],
  },
  {
    id: "window_calibration",
    name: "Window Auto-Up Calibration",
    description: "Run body module window normalization where supported.",
    category: "Body",
    icon: "square",
    dangerous: false,
    obdCommands: [...commonStart(BCM), routine("FF50", "Run window normalization/calibration routine"), ...finish],
    steps: ["Ignition ON", "Run routine", "Test one-touch up/down"],
  },
  {
    id: "sunroof_calibration",
    name: "Sunroof Calibration",
    description: "Run sunroof position normalization where supported.",
    category: "Body",
    icon: "sun",
    dangerous: false,
    obdCommands: [...commonStart(BCM), routine("FF51", "Run sunroof calibration routine"), ...finish],
    steps: ["Close sunroof", "Run calibration", "Let cycle finish", "Test operation"],
  },
  {
    id: "battery_registration",
    name: "Battery Registration",
    description: "Register replacement battery metadata where supported by BCM/energy module.",
    category: "Battery",
    icon: "battery-charging",
    dangerous: false,
    obdCommands: [...commonStart(BCM), writeData("F19041474D303030313030", "Write sample battery type/capacity placeholder data"), routine("FF60", "Run battery registration routine"), ...finish],
    steps: ["Install correct battery", "Enter battery specs if app prompts", "Run registration", "Verify charging voltage"],
  },
  {
    id: "alternator_reset",
    name: "Charging System Reset",
    description: "Reset charging/energy management adaptives where supported.",
    category: "Battery",
    icon: "zap",
    dangerous: false,
    obdCommands: [...commonStart(BCM), routine("FF61", "Run charging system adaptive reset routine"), ...finish],
    steps: ["Battery healthy", "Run reset", "Idle 20 minutes", "Verify charging output"],
  },
  {
    id: "hvac_blend",
    name: "HVAC Blend Door Calibration",
    description: "Calibrate HVAC actuator end stops where supported.",
    category: "HVAC",
    icon: "thermometer",
    dangerous: false,
    obdCommands: [...commonStart(HVAC), routine("FF70", "Run HVAC actuator calibration routine"), ...finish],
    steps: ["Ignition ON", "HVAC off", "Run routine", "Wait for all doors to stop moving"],
  },
  {
    id: "ac_service",
    name: "A/C Service Reset",
    description: "Reset A/C service counter where supported.",
    category: "HVAC",
    icon: "wind",
    dangerous: false,
    obdCommands: [...commonStart(HVAC), routine("FF71", "Run A/C service counter reset routine"), ...finish],
    steps: ["Complete A/C service", "Run reset", "Verify no HVAC warnings"],
  },

  // ── KEYS & SECURITY ──────────────────────────────────────────────────────────
  {
    id: "key_fob_add",
    name: "Add Key Fob / Remote",
    description: "Program an additional RF key fob to the BCM",
    category: "Keys & Security",
    icon: "radio",
    dangerous: false,
    requiresEngineOff: true,
    steps: [
      "Have all existing fobs you want to keep on hand",
      "Ignition ON, engine off",
      "App puts BCM into fob learn mode",
      "Press any button on each new fob within 30 seconds",
      "BCM confirms each fob with horn chirp",
      "App exits learn mode — test all buttons",
    ],
    obdCommands: [
      ...commonStart(BCM),
      { cmd: "2703",       desc: "Security seed request",      expectOk: true, timeoutMs: 2000 },
      { cmd: "2704CAFE",   desc: "Security key response",      expectOk: true, timeoutMs: 2000 },
      routine("00D0", "Enter fob learn mode"),
      { cmd: "3E00",       desc: "Keep-alive — press fob now", expectOk: false, timeoutMs: 1000 },
      { cmd: "3103D001",   desc: "Check fob learned",          expectOk: true, timeoutMs: 10000 },
      { cmd: "3102D000",   desc: "Exit learn mode",            expectOk: true, timeoutMs: 2000 },
      ...finish,
    ],
  },
  {
    id: "key_fob_relearn_all",
    name: "Relearn All Remotes",
    description: "Erase all stored fob IDs and relearn from scratch",
    category: "Keys & Security",
    icon: "refresh-cw",
    dangerous: true,
    warning: "This erases ALL currently programmed remotes. Have every fob you want to keep on hand before proceeding.",
    requiresEngineOff: true,
    steps: [
      "Gather ALL key fobs you want to keep",
      "Have a working mechanical key available",
      "App erases all fob IDs from BCM memory",
      "BCM enters full learn mode — press a button on each fob within 60 seconds",
      "Cycle ignition to end session — test every fob",
    ],
    obdCommands: [
      ...commonStart(BCM),
      { cmd: "2703",       desc: "Security seed request",       expectOk: true, timeoutMs: 2000 },
      { cmd: "2704CAFE",   desc: "Security key response",       expectOk: true, timeoutMs: 2000 },
      writeData("0D0000", "Erase all fob IDs"),
      routine("00D0", "Enter full fob learn mode"),
      { cmd: "3E00",       desc: "Keep-alive — press all fobs", expectOk: false, timeoutMs: 1000 },
      { cmd: "3103D001",   desc: "Check fobs learned",          expectOk: true, timeoutMs: 15000 },
      { cmd: "3102D000",   desc: "Exit learn mode",             expectOk: true, timeoutMs: 2000 },
      ...finish,
    ],
  },
  {
    id: "transponder_key_add",
    name: "Add Transponder / Chip Key",
    description: "Program a new IMMO transponder key so the engine will start",
    category: "Keys & Security",
    icon: "key",
    dangerous: false,
    requiresEngineOff: true,
    steps: [
      "Obtain a compatible blank key with correct chip (ID46, PCF7936, ID63 etc.)",
      "Have key blade cut to your VIN by a locksmith",
      "Insert a currently working key and cycle ignition ON → OFF 3 times rapidly",
      "App puts immobilizer in learn mode",
      "Insert new key and turn ignition ON — hold up to 10 seconds",
      "Security light changes pattern to confirm chip accepted",
      "Remove and test — engine should crank and start",
    ],
    obdCommands: [
      ...commonStart(BCM),
      { cmd: "2703",       desc: "Security seed request",           expectOk: true, timeoutMs: 2000 },
      { cmd: "2704A5B4",   desc: "Security key response",           expectOk: true, timeoutMs: 2000 },
      routine("00F1", "Enter transponder key learn mode"),
      { cmd: "3E00",       desc: "Keep-alive — insert new key now", expectOk: false, timeoutMs: 1000 },
      { cmd: "3103F101",   desc: "Check transponder learned",       expectOk: true, timeoutMs: 10000 },
      { cmd: "3102F100",   desc: "Exit learn mode",                 expectOk: true, timeoutMs: 2000 },
      ...finish,
    ],
  },
  {
    id: "immo_relearn_bcm",
    name: "IMMO Relearn After BCM Swap",
    description: "Re-synchronize immobilizer and ECM after replacing the BCM or ECM",
    category: "Keys & Security",
    icon: "cpu",
    dangerous: true,
    warning: "Requires the vehicle factory PIN code from the original BCM sticker or dealer records. Without the correct seed/key the module will not accept new keys.",
    steps: [
      "New BCM must be VIN-flashed before this step",
      "App enters security access — requires vehicle PIN",
      "Module syncs with ECM and transponder ring after security access granted",
      "Insert each physical key and trigger IMMO learn sequence",
      "Security light must extinguish when correct key is inserted",
      "Perform test start cycle to confirm engine authorization",
    ],
    obdCommands: [
      ...commonStart(BCM),
      { cmd: "2705",         desc: "Request high-security seed",     expectOk: true, timeoutMs: 2000 },
      { cmd: "2706A5B4C3D2", desc: "Send security key (PIN-derived)", expectOk: true, timeoutMs: 2000 },
      routine("00F2", "Start IMMO-ECM adaptation"),
      { cmd: "3E00",         desc: "Keep-alive during sync",         expectOk: false, timeoutMs: 1000 },
      { cmd: "3103F201",     desc: "Check adaptation complete",      expectOk: true, timeoutMs: 15000 },
      routine("00F1", "Enter transponder key learn mode"),
      { cmd: "3E00",         desc: "Keep-alive — insert keys now",   expectOk: false, timeoutMs: 1000 },
      { cmd: "3103F101",     desc: "Check keys learned",             expectOk: true, timeoutMs: 15000 },
      { cmd: "3102F100",     desc: "Exit learn mode",                expectOk: true, timeoutMs: 2000 },
      ...finish,
    ],
  },
  {
    id: "all_keys_lost",
    name: "All Keys Lost Recovery",
    description: "Emergency IMMO reset when all transponder keys are lost — requires security PIN",
    category: "Keys & Security",
    icon: "unlock",
    dangerous: true,
    warning: "Grants engine start access to newly programmed keys. Requires factory PIN from original BCM sticker. Confirm you are the registered owner.",
    steps: [
      "Obtain vehicle immobilizer PIN from original BCM sticker, dealer, or EEPROM read",
      "App enters all-keys-lost mode using security PIN exchange",
      "Module erases transponder table — all old keys invalidated",
      "Program at least one new blank transponder key (see Add Transponder Key)",
      "Test start — security light must extinguish, engine must crank",
      "Program a spare key immediately — never drive with only one key",
    ],
    obdCommands: [
      ...commonStart(BCM),
      { cmd: "2705",         desc: "Request security seed",          expectOk: true, timeoutMs: 2000 },
      { cmd: "2706A5B4C3D2", desc: "Send security key (PIN-derived)", expectOk: true, timeoutMs: 2000 },
      writeData("0F0000", "Erase all transponder IDs"),
      { cmd: "3103F301",     desc: "Verify erase complete",          expectOk: true, timeoutMs: 5000 },
      routine("00F1", "Enter key learn mode"),
      { cmd: "3E00",         desc: "Keep-alive — insert new key now", expectOk: false, timeoutMs: 1000 },
      { cmd: "3103F101",     desc: "Check key learned",              expectOk: true, timeoutMs: 10000 },
      { cmd: "3102F100",     desc: "Exit learn mode",                expectOk: true, timeoutMs: 2000 },
      ...finish,
    ],
  },
  {
    id: "remote_start_relearn",
    name: "Remote Start Module Relearn",
    description: "Re-pair an aftermarket or OEM remote start module after key or BCM changes",
    category: "Keys & Security",
    icon: "play-circle",
    dangerous: false,
    steps: [
      "Confirm remote start module is wired and powered",
      "App puts BCM into remote start pairing mode",
      "Use working programmed fob: press Lock 3× — module confirms with LED/siren",
      "Drive cycle 15 minutes to complete all IMMO handshakes",
      "Test remote start from full range",
    ],
    obdCommands: [
      ...commonStart(BCM),
      { cmd: "2703",       desc: "Security seed request",            expectOk: true, timeoutMs: 2000 },
      { cmd: "2704A5B4",   desc: "Security key response",            expectOk: true, timeoutMs: 2000 },
      routine("00E1", "Enter remote start pair mode"),
      { cmd: "3E00",       desc: "Keep-alive — press fob Lock 3×",  expectOk: false, timeoutMs: 1000 },
      { cmd: "3103E101",   desc: "Confirm pairing complete",         expectOk: true, timeoutMs: 10000 },
      { cmd: "3102E100",   desc: "Exit pair mode",                   expectOk: true, timeoutMs: 2000 },
      ...finish,
    ],
  },
  {
    id: "fob_signal_test",
    name: "Key Fob Signal Test",
    description: "Verify each fob button transmits a valid RF signal to the BCM receiver",
    category: "Keys & Security",
    icon: "wifi",
    dangerous: false,
    steps: [
      "App puts BCM into RF signal monitor mode",
      "Press each fob button — BCM logs signal strength and button ID",
      "Results show LOCK, UNLOCK, TRUNK, PANIC signal data",
      "Weak or missing signal = dead battery or damaged fob",
      "Replace CR2032 / CR2025 coin cell if signal is weak",
    ],
    obdCommands: [
      ...commonStart(BCM),
      routine("00E2", "Enter RF signal monitor mode"),
      { cmd: "3E00",       desc: "Keep-alive — press fob buttons",  expectOk: false, timeoutMs: 1000 },
      { cmd: "3103E201",   desc: "Read RF signal log",              expectOk: true, timeoutMs: 8000 },
      { cmd: "3102E200",   desc: "Exit monitor mode",               expectOk: true, timeoutMs: 2000 },
      ...finish,
    ],
  },
  {
    id: "passive_entry_calibrate",
    name: "Passive Entry Antenna Cal",
    description: "Calibrate LF antenna detection zones for keyless entry and push-button start",
    category: "Keys & Security",
    icon: "crosshair",
    dangerous: false,
    steps: [
      "Ensure all door/trunk LF antennas are connected",
      "App broadcasts calibration sweep to each antenna in sequence",
      "Walk around the vehicle with a programmed fob while calibration runs",
      "System maps detection bubble per door zone",
      "Confirm push-button start only activates with fob inside cabin",
    ],
    obdCommands: [
      ...commonStart(BCM),
      { cmd: "2703",       desc: "Security seed request",            expectOk: true, timeoutMs: 2000 },
      { cmd: "2704A5B4",   desc: "Security key response",            expectOk: true, timeoutMs: 2000 },
      routine("00E3", "Start LF antenna calibration"),
      { cmd: "3E00",       desc: "Keep-alive — walk vehicle now",    expectOk: false, timeoutMs: 1000 },
      { cmd: "3103E301",   desc: "Check calibration complete",       expectOk: true, timeoutMs: 30000 },
      ...finish,
    ],
  },
];