kind = "mobile"
previewPath = "/"
title = "OBD2 Scanner"
version = "1.0.0"
id = "artifacts/obd2-scanner"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24966

[services.development]
run = "pnpm --filter @workspace/obd2-scanner run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/obd2-scanner", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/obd2-scanner", "run", "serve" ]

[services.env]
PORT = "24966"
BASE_PATH = "/"
