export interface BiDiCommand {
  id: string;
  name: string;
  description: string;
  category: string;
  command: string;
  dangerous: boolean;
  duration: number;
  icon: string;
}

export const CATEGORIES = [
  "Cooling",
  "Fuel System",
  "Emissions",
  "Ignition",
  "Transmission",
  "HVAC",
  "Suspension",
  "Injection",
];

export const BIDI_COMMANDS: BiDiCommand[] = [
  {
    id: "fan_low",
    name: "Cooling Fan Low",
    description: "Activate radiator cooling fan at low speed",
    category: "Cooling",
    command: "0801",
    dangerous: false,
    duration: 5000,
    icon: "wind",
  },
  {
    id: "fan_high",
    name: "Cooling Fan High",
    description: "Activate radiator cooling fan at high speed",
    category: "Cooling",
    command: "0802",
    dangerous: false,
    duration: 5000,
    icon: "wind",
  },
  {
    id: "ac_compressor",
    name: "A/C Compressor",
    description: "Activate A/C compressor clutch",
    category: "HVAC",
    command: "0803",
    dangerous: false,
    duration: 3000,
    icon: "thermometer",
  },
  {
    id: "fuel_pump",
    name: "Fuel Pump",
    description: "Activate fuel pump relay for pressure test",
    category: "Fuel System",
    command: "0804",
    dangerous: false,
    duration: 5000,
    icon: "droplet",
  },
  {
    id: "purge_valve",
    name: "EVAP Purge Valve",
    description: "Open EVAP purge solenoid valve",
    category: "Emissions",
    command: "0805",
    dangerous: false,
    duration: 3000,
    icon: "cloud",
  },
  {
    id: "egr_valve",
    name: "EGR Valve",
    description: "Open EGR valve to check operation",
    category: "Emissions",
    command: "0806",
    dangerous: false,
    duration: 3000,
    icon: "refresh-cw",
  },
  {
    id: "iac_motor",
    name: "Idle Air Control",
    description: "Drive IAC motor to test idle control",
    category: "Fuel System",
    command: "0807",
    dangerous: false,
    duration: 3000,
    icon: "activity",
  },
  {
    id: "vvt_solenoid",
    name: "VVT Solenoid",
    description: "Activate variable valve timing solenoid",
    category: "Ignition",
    command: "0808",
    dangerous: false,
    duration: 3000,
    icon: "zap",
  },
  {
    id: "inj_1",
    name: "Injector 1 Test",
    description: "Perform balance test on injector cylinder 1",
    category: "Injection",
    command: "0811",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "inj_2",
    name: "Injector 2 Test",
    description: "Perform balance test on injector cylinder 2",
    category: "Injection",
    command: "0812",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "inj_3",
    name: "Injector 3 Test",
    description: "Perform balance test on injector cylinder 3",
    category: "Injection",
    command: "0813",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "inj_4",
    name: "Injector 4 Test",
    description: "Perform balance test on injector cylinder 4",
    category: "Injection",
    command: "0814",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "inj_5",
    name: "Injector 5 Test",
    description: "Perform balance test on injector cylinder 5",
    category: "Injection",
    command: "0815",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "inj_6",
    name: "Injector 6 Test",
    description: "Perform balance test on injector cylinder 6",
    category: "Injection",
    command: "0816",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "inj_7",
    name: "Injector 7 Test",
    description: "Perform balance test on injector cylinder 7",
    category: "Injection",
    command: "0817",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "inj_8",
    name: "Injector 8 Test",
    description: "Perform balance test on injector cylinder 8",
    category: "Injection",
    command: "0818",
    dangerous: true,
    duration: 2000,
    icon: "droplets",
  },
  {
    id: "starter_relay",
    name: "Starter Relay",
    description: "Activate starter relay (short pulse only)",
    category: "Ignition",
    command: "0809",
    dangerous: true,
    duration: 500,
    icon: "power",
  },
  {
    id: "abs_pump",
    name: "ABS Pump Motor",
    description: "Test ABS hydraulic pump operation",
    category: "Suspension",
    command: "0810",
    dangerous: true,
    duration: 3000,
    icon: "disc",
  },
  {
    id: "tc_solenoid",
    name: "TCC Solenoid",
    description: "Apply torque converter clutch solenoid",
    category: "Transmission",
    command: "0820",
    dangerous: false,
    duration: 3000,
    icon: "settings",
  },
  {
    id: "shift_sol_a",
    name: "Shift Solenoid A",
    description: "Actuate transmission shift solenoid A",
    category: "Transmission",
    command: "0821",
    dangerous: true,
    duration: 2000,
    icon: "git-branch",
  },
  {
    id: "shift_sol_b",
    name: "Shift Solenoid B",
    description: "Actuate transmission shift solenoid B",
    category: "Transmission",
    command: "0822",
    dangerous: true,
    duration: 2000,
    icon: "git-branch",
  },
  {
    id: "canister_vent",
    name: "Canister Vent Valve",
    description: "Close EVAP canister vent valve for leak test",
    category: "Emissions",
    command: "0823",
    dangerous: false,
    duration: 3000,
    icon: "filter",
  },
  {
    id: "secondary_air",
    name: "Secondary Air Pump",
    description: "Activate secondary air injection pump",
    category: "Emissions",
    command: "0824",
    dangerous: false,
    duration: 5000,
    icon: "wind",
  },
];
