export interface OBDProtocol {
  id: string;
  atCode: string;
  name: string;
  shortName: string;
  speed: string;
  bits: string;
  pins: string;
  era: string;
  coverage: string[];
  notes: string;
  category: "CAN" | "Legacy" | "Heavy Duty" | "Manufacturer";
}

export interface ATCommand {
  command: string;
  description: string;
  example?: string;
  category: string;
}

export const OBD_PROTOCOLS: OBDProtocol[] = [
  {
    id: "SP0",
    atCode: "ATSP0",
    name: "Automatic Detection",
    shortName: "AUTO",
    speed: "Varies",
    bits: "Varies",
    pins: "Varies",
    era: "All",
    coverage: ["All OBD2 vehicles"],
    notes: "ELM327 tries protocols SP1–SP9 in sequence. Adds ~5s delay on first connect. Best for unknown vehicles.",
    category: "CAN",
  },
  {
    id: "SP1",
    atCode: "ATSP1",
    name: "SAE J1850 PWM",
    shortName: "J1850 PWM",
    speed: "41.6 kbps",
    bits: "Variable length",
    pins: "Pin 2",
    era: "1996–2008",
    coverage: ["Ford", "Lincoln", "Mercury"],
    notes: "Ford's primary legacy protocol. 41.6 kbps PWM. Used by EEC-IV/V powertrain and body modules on F-150, Mustang, Explorer, etc. NOT used on CAN-enabled Fords (2008+).",
    category: "Legacy",
  },
  {
    id: "SP2",
    atCode: "ATSP2",
    name: "SAE J1850 VPW",
    shortName: "J1850 VPW",
    speed: "10.4 kbps",
    bits: "Variable length",
    pins: "Pin 2",
    era: "1994–2004",
    coverage: ["GM", "Chevrolet", "GMC", "Buick", "Cadillac", "Oldsmobile", "Pontiac", "Saturn"],
    notes: "GM's primary legacy protocol. Slower but more robust than PWM. Used with Class 2 serial data. Replaced by GMLAN (CAN) on 2003+ GM vehicles.",
    category: "Legacy",
  },
  {
    id: "SP3",
    atCode: "ATSP3",
    name: "ISO 9141-2",
    shortName: "ISO 9141",
    speed: "10.4 kbps",
    bits: "8-bit",
    pins: "Pin 7 (K-Line), Pin 15 (L-Line optional)",
    era: "1996–2004",
    coverage: ["Chrysler", "European", "Asian (non-Honda/Toyota)", "BMW (older)", "Mercedes (older)"],
    notes: "5-baud slow initiation. K-Line single-wire serial. L-Line used for wake-up on some vehicles. Very common on European imports 1996–2003.",
    category: "Legacy",
  },
  {
    id: "SP4",
    atCode: "ATSP4",
    name: "ISO 14230-4 KWP (5-baud init)",
    shortName: "KWP 5-baud",
    speed: "10.4 kbps",
    bits: "8-bit",
    pins: "Pin 7 (K-Line)",
    era: "1999–2008",
    coverage: ["VW", "Audi", "BMW", "Mercedes-Benz", "Volvo", "Saab", "Asian imports"],
    notes: "Keyword Protocol 2000 with slow 5-baud initialization. Used for legacy body/comfort modules that don't respond to fast init. Needed for older VAG immobilizer, airbag, and instrument cluster access.",
    category: "Legacy",
  },
  {
    id: "SP5",
    atCode: "ATSP5",
    name: "ISO 14230-4 KWP (fast init)",
    shortName: "KWP Fast",
    speed: "10.4–115.2 kbps",
    bits: "8-bit",
    pins: "Pin 7 (K-Line)",
    era: "1999–2010",
    coverage: ["VW", "Audi", "BMW", "Mercedes-Benz", "Renault", "Peugeot", "Citroën", "Mitsubishi"],
    notes: "Faster KWP initialization (25 ms break + 25 ms idle). Most common for European diagnostic sessions before CAN became universal. Still needed for some ECU sub-functions even on CAN cars.",
    category: "Legacy",
  },
  {
    id: "SP6",
    atCode: "ATSP6",
    name: "ISO 15765-4 CAN (11-bit, 500 kbaud)",
    shortName: "CAN 11/500",
    speed: "500 kbps",
    bits: "11-bit ID",
    pins: "Pin 6 (CAN High), Pin 14 (CAN Low)",
    era: "2003–present",
    coverage: ["Most modern vehicles", "US domestic 2008+", "European 2004+", "Asian 2005+"],
    notes: "The dominant modern protocol. Mandatory on all US OBD2 vehicles from 2008. ECM/PCM address 0x7E0, response 0x7E8. TCM=7E1/7E9, BCM=7B0/7B8.",
    category: "CAN",
  },
  {
    id: "SP7",
    atCode: "ATSP7",
    name: "ISO 15765-4 CAN (29-bit, 500 kbaud)",
    shortName: "CAN 29/500",
    speed: "500 kbps",
    bits: "29-bit ID",
    pins: "Pin 6, Pin 14",
    era: "2003–present",
    coverage: ["Mercedes-Benz", "BMW (some)", "Volvo", "some European vehicles"],
    notes: "Extended CAN ID format. Mercedes-Benz uses 29-bit CAN exclusively for powertrain. Request: 0x18DB33F1, Response from ECU: 0x18DAF10X.",
    category: "CAN",
  },
  {
    id: "SP8",
    atCode: "ATSP8",
    name: "ISO 15765-4 CAN (11-bit, 250 kbaud)",
    shortName: "CAN 11/250",
    speed: "250 kbps",
    bits: "11-bit ID",
    pins: "Pin 6, Pin 14",
    era: "2003–present",
    coverage: ["Some GM vehicles", "Some Chrysler", "Hybrid/EV secondary buses"],
    notes: "Slower 250kbps CAN. Used by some GM body modules and on the secondary GMLAN low-speed bus. If SP6 fails try SP8.",
    category: "CAN",
  },
  {
    id: "SP9",
    atCode: "ATSP9",
    name: "ISO 15765-4 CAN (29-bit, 250 kbaud)",
    shortName: "CAN 29/250",
    speed: "250 kbps",
    bits: "29-bit ID",
    pins: "Pin 6, Pin 14",
    era: "2003–present",
    coverage: ["Some European vehicles", "Trucks", "Some Mercedes body modules"],
    notes: "Slowest CAN variant. Occasionally used for body/chassis buses on European vehicles. Rare for powertrain.",
    category: "CAN",
  },
  {
    id: "SPA",
    atCode: "ATSPA",
    name: "SAE J1939 CAN (29-bit, 250 kbaud)",
    shortName: "J1939",
    speed: "250 kbps",
    bits: "29-bit PGN",
    pins: "Pin 6, Pin 14",
    era: "1994–present",
    coverage: ["Semi-trucks", "Heavy equipment", "Buses", "Construction machinery", "RVs"],
    notes: "Heavy-duty truck standard. Uses PGN (Parameter Group Number) format instead of OBD2 Mode/PID. Pins 6+14 like car CAN but at 250kbps. Requires J1939 PGN decoder (not standard OBD2).",
    category: "Heavy Duty",
  },
  {
    id: "SPB",
    atCode: "ATSPB",
    name: "User-Defined CAN 1",
    shortName: "USER CAN 1",
    speed: "Configurable",
    bits: "Configurable",
    pins: "Pin 6, Pin 14",
    era: "Custom",
    coverage: ["Custom implementations", "Race/tuning ECUs"],
    notes: "Fully configurable CAN protocol. Set speed with ATBRT, ID format with ATBI. Use for proprietary or racing ECUs that don't follow ISO 15765-4 framing.",
    category: "CAN",
  },
  {
    id: "SPC",
    atCode: "ATSPC",
    name: "User-Defined CAN 2",
    shortName: "USER CAN 2",
    speed: "Configurable",
    bits: "Configurable",
    pins: "Pin 6, Pin 14",
    era: "Custom",
    coverage: ["Custom implementations", "Second CAN bus"],
    notes: "Second fully configurable CAN channel. Useful for accessing a second CAN bus (e.g. a vehicle with both a high-speed powertrain CAN and a low-speed body CAN on different pins).",
    category: "CAN",
  },
];

export const AT_COMMANDS: ATCommand[] = [
  { command: "ATZ", description: "Reset all settings and warm-start ELM327", category: "General" },
  { command: "ATD", description: "Set all parameters to factory defaults", category: "General" },
  { command: "ATI", description: "Print firmware version string (e.g. 'ELM327 v2.2')", category: "General" },
  { command: "ATRV", description: "Read battery voltage via internal divider", example: "12.4V", category: "General" },
  { command: "ATL0 / ATL1", description: "Disable / Enable linefeed after carriage return", category: "General" },
  { command: "ATE0 / ATE1", description: "Disable / Enable command echo", category: "General" },
  { command: "ATS0 / ATS1", description: "Disable / Enable space printing in responses", category: "General" },
  { command: "ATH0 / ATH1", description: "Disable / Enable message headers in responses", category: "Formatting" },
  { command: "ATCAF0 / ATCAF1", description: "Disable / Enable CAN auto-formatting (raw mode when 0)", category: "CAN" },
  { command: "ATAR", description: "Automatic Receive — set reply filter to last TX header", category: "CAN" },
  { command: "ATSH XXX", description: "Set header bytes for outgoing messages", example: "ATSH 7E0", category: "CAN" },
  { command: "ATSP X", description: "Set protocol (0=auto, 1–C as listed)", example: "ATSP6", category: "Protocol" },
  { command: "ATDP", description: "Describe current protocol in English", category: "Protocol" },
  { command: "ATDPN", description: "Describe current protocol by number", category: "Protocol" },
  { command: "ATMA", description: "Monitor All — stream all CAN bus traffic (press any key to stop)", category: "Monitor" },
  { command: "ATMT XX", description: "Monitor for Transmit ID XX only", example: "ATMT 7E8", category: "Monitor" },
  { command: "ATST XX", description: "Set timeout in multiples of 4ms", example: "ATST FF = 1020ms", category: "Timing" },
  { command: "ATAT0 / ATAT2", description: "Adaptive timing off / maximum aggressiveness", category: "Timing" },
  { command: "ATFCSM0/1/2", description: "Flow Control mode: off / on / user-defined", category: "CAN" },
  { command: "ATFCSD XX XX XX", description: "Flow Control Send Data bytes", category: "CAN" },
  { command: "ATAT1", description: "Adaptive timing mode 1 (default — balances speed and reliability)", category: "Timing" },
  { command: "ATBI", description: "Bypass Initialization (skip slow init, go straight to send)", category: "Protocol" },
  { command: "ATIIA XX", description: "Set ISO Init Address for KWP init", example: "ATIIA 33", category: "Legacy" },
  { command: "ATIB XX", description: "Set ISO Baud rate divisor", category: "Legacy" },
  { command: "ATWM [bytes]", description: "Set Wakeup Message bytes (periodic wakeup for sleep-prone ECUs)", category: "Legacy" },
  { command: "ATWS", description: "Warm Start — reset but keep current protocol settings", category: "General" },
  { command: "ATPPS", description: "Print all programmable parameters and their current values", category: "Advanced" },
  { command: "ATPP XX SV YY", description: "Set programmable parameter XX to value YY", category: "Advanced" },
  { command: "ATRTSTO", description: "Restore factory OBD timeout default", category: "Advanced" },
];

export const OBD2_PINS = [
  { pin: 1, label: "Manufacturer Discretionary", description: "Unused in standard OBD2. BMW uses for ENET (Ethernet TX+). Some VAG use for K-Line." },
  { pin: 2, label: "J1850 Bus (+)", description: "SAE J1850 PWM/VPW data line. Used by Ford (PWM) and GM (VPW). Not present on CAN-only vehicles." },
  { pin: 3, label: "Manufacturer Discretionary", description: "Chrysler CCD Bus (+) on 1994–2004 Chrysler/Dodge/Jeep products." },
  { pin: 4, label: "Chassis Ground", description: "Vehicle body ground. Always connected to chassis. Use as reference ground for multimeter tests." },
  { pin: 5, label: "Signal Ground", description: "ECM/PCM signal reference ground. Should be <50mV relative to pin 4. Higher = ground fault." },
  { pin: 6, label: "CAN High (J-2284)", description: "CAN bus High signal. ~2.5–3.5V. Present on all 2008+ US OBD2 vehicles. Also used on ENET (BMW F-series)." },
  { pin: 7, label: "ISO 9141-2 / KWP K-Line", description: "K-Line for ISO 9141-2 and KWP2000 protocols. Idle high (~12V). Used for legacy European diagnostics." },
  { pin: 8, label: "Manufacturer Discretionary", description: "Rarely populated. BMW uses for ENET (Ethernet RX+). Toyota uses for bus-detect on some models." },
  { pin: 9, label: "Manufacturer Discretionary", description: "BMW ENET (Ethernet TX–). Rarely used in standard OBD2." },
  { pin: 10, label: "J1850 Bus (–)", description: "SAE J1850 VPW ground reference. Only on GM pre-CAN vehicles." },
  { pin: 11, label: "Manufacturer Discretionary", description: "Chrysler CCD Bus (–). Also used as second K-Line on some Mitsubishi." },
  { pin: 12, label: "Manufacturer Discretionary", description: "Chrysler SCI Transmit. Ford uses for SCP (Standard Corporate Protocol) on some modules." },
  { pin: 13, label: "Manufacturer Discretionary", description: "Chrysler SCI Receive. Used on Chrysler/Dodge DRBIII-compatible interfaces." },
  { pin: 14, label: "CAN Low (J-2284)", description: "CAN bus Low signal. ~1.5–2.5V. Differential with pin 6 drives data. Present on all CAN vehicles." },
  { pin: 15, label: "ISO 9141-2 L-Line", description: "L-Line used for ECU wake-up during ISO 9141-2 5-baud init. Not needed for KWP fast-init." },
  { pin: 16, label: "Battery Power (+12V)", description: "Unswitched 12V from battery. Always present — powers the scan adapter. Check here first if adapter won't power on." },
];
