export type TrickCategory =
  | "Pin Jump"
  | "Diagnostic Mode"
  | "ELM327 Command"
  | "Manufacturer Secret"
  | "Key & Immobilizer"
  | "Community Tip";

export interface SecretTrick {
  id: string;
  title: string;
  category: TrickCategory;
  makes: string[];
  difficulty: "Easy" | "Medium" | "Advanced";
  description: string;
  steps?: string[];
  pinNote?: string;
  warning?: string;
  source: "builtin" | "user";
  createdAt?: string;
}

export const BUILT_IN_TRICKS: SecretTrick[] = [
  {
    id: "obd2_pin16_test",
    title: "Verify OBD2 Power: Pin 16 → 12V Always-On",
    category: "Pin Jump",
    makes: ["All"],
    difficulty: "Easy",
    description: "OBD2 pin 16 is unswitched battery power (always on regardless of ignition). Use a multimeter to confirm 12V between pin 16 (+) and pin 4 or 5 (ground) before connecting any adapter. Low voltage here means a blown fuse.",
    steps: [
      "Set multimeter to DC Voltage, 20V range",
      "Probe: Red to OBD2 pin 16, Black to pin 4 or 5",
      "Expected reading: 11.5–13.5V with ignition off, 13.5–14.8V running",
      "Below 10V: check fuse F37 (or equivalent for your make) in the underhood fuse box",
    ],
    pinNote: "Pin 16 (+), Pin 4 Chassis GND, Pin 5 Signal GND",
    source: "builtin",
  },
  {
    id: "can_sniff_test",
    title: "CAN Bus Health Check: Pin 6 vs Pin 14",
    category: "Pin Jump",
    makes: ["All"],
    difficulty: "Easy",
    description: "On any CAN vehicle, you can verify the CAN bus is alive using a multimeter. With ignition ON, CAN High should sit ~2.5–3.5V and CAN Low ~1.5–2.5V. Differential between them should be ~1–2V. Equal voltages = bus fault or terminated incorrectly.",
    steps: [
      "Ignition ON (engine not required)",
      "Probe pin 6 (CAN High): expect 2.5–3.5V DC",
      "Probe pin 14 (CAN Low): expect 1.5–2.5V DC",
      "Differential (pin 6 minus pin 14): should be ~1–2V",
      "Both pins identical voltage (e.g. both 2.5V): CAN bus is silent — check for open circuit or faulty module",
      "Both pins at 0V: power issue to CAN network",
      "Use an oscilloscope for full waveform — should see square-wave activity",
    ],
    pinNote: "Pin 6: CAN High, Pin 14: CAN Low",
    source: "builtin",
  },
  {
    id: "toyota_te1_diagnostic",
    title: "Toyota / Lexus: Bridge TE1 to E1 for Diagnostic Mode",
    category: "Pin Jump",
    makes: ["Toyota", "Lexus"],
    difficulty: "Easy",
    description: "On pre-2005 Toyota and Lexus with the OBDI-style 17-pin diagnostic connector (in addition to OBDII), shorting TE1 to E1 forces the ECM into diagnostic mode. The Check Engine light will flash stored codes in a morse-code pattern. This works even without a scan tool.",
    steps: [
      "Locate the 17-pin Toyota diagnostic connector (usually in engine bay or kick panel)",
      "Ignition ON, engine off",
      "Short TE1 (pin) to E1 (pin) with a jumper wire or paperclip",
      "Count Check Engine light flashes: long flash = 10, short flash = 1",
      "Example: 2 long + 3 short = code 23",
      "Normal (no faults): light flashes rapidly and continuously",
    ],
    pinNote: "17-pin Toyota/Lexus diagnostic connector: TE1 → E1",
    warning: "This is the older OBDI-style connector on pre-OBD2 vehicles. On 1996+ OBD2-compliant Toyotas, use the standard scan tool method.",
    source: "builtin",
  },
  {
    id: "honda_service_check",
    title: "Honda: Short Service Check Connector to Enter Diagnostic Mode",
    category: "Pin Jump",
    makes: ["Honda", "Acura"],
    difficulty: "Easy",
    description: "Honda OBDI vehicles (pre-1996) have a 2-pin 'Service Check Connector' (SCS) usually located under the dashboard on the passenger side. Shorting these two pins with a paperclip puts the ECU into flash-code diagnostic mode.",
    steps: [
      "Locate the 2-pin SCS connector (blue or brown connector, usually taped near the fuse box)",
      "Ignition ON, engine off",
      "Short the two SCS pins with a wire or paperclip",
      "Watch the D4 indicator light (manual trans: CEL) for flash codes",
      "Count flashes in the same way as Toyota: long = 10, short = 1",
      "To clear codes: remove backup fuse for 10 seconds (older models) or use the SCS method with ignition cycling",
    ],
    pinNote: "2-pin SCS connector: short both pins",
    source: "builtin",
  },
  {
    id: "gm_aldl_bridge",
    title: "GM: ALDL Pin 5 to Ground = Diagnostic Mode (Pre-OBD2)",
    category: "Pin Jump",
    makes: ["GM", "Chevrolet", "GMC", "Buick", "Cadillac", "Pontiac"],
    difficulty: "Easy",
    description: "On older GM vehicles with the 12-pin ALDL (Assembly Line Diagnostic Link) connector, grounding pin 5 (ALDL Test Terminal) puts the ECM into field service mode. The Check Engine light will flash diagnostic codes.",
    steps: [
      "Locate the 12-pin ALDL connector (usually under the dash, driver's side)",
      "Ignition ON, engine off",
      "Using a jumper wire, connect ALDL pin 5 (Test Terminal) to ALDL pin 4 (Ground) or any chassis ground",
      "Read flash codes from Check Engine light",
      "Code 12 (one long, two short) = normal, no faults",
      "Each fault code repeats 3 times before moving to the next",
      "Ignition OFF ends diagnostic mode",
    ],
    pinNote: "ALDL 12-pin: Pin 5 (Test) → Pin 4 (GND)",
    source: "builtin",
  },
  {
    id: "ford_pats_relearn",
    title: "Ford PATS: Security Relearn Without IDS (Specific Models)",
    category: "Manufacturer Secret",
    makes: ["Ford", "Lincoln", "Mercury"],
    difficulty: "Advanced",
    description: "On some Ford PATS (Passive Anti-Theft System) Tier I vehicles, you can program transponder keys without a dealer IDS tool by using two currently-working programmed keys. This is the 'two-key' programming method.",
    steps: [
      "You need TWO currently working Ford-coded transponder keys",
      "Insert Key 1 (working) and turn to RUN for at least 1 second",
      "Within 5 seconds, switch to Key 2 (second working key) and turn to RUN for 1 second",
      "Security LED should go off and stay on for 3 seconds, then flash rapidly",
      "Within 10 seconds, insert the NEW blank key and turn to RUN",
      "If accepted: security LED will go off momentarily, then return to normal",
      "Cycle ignition off and test new key",
    ],
    warning: "Only works on PATS Tier I (older) systems. PATS Tier II, III require IDS or a J2534 pass-through programmer.",
    source: "builtin",
  },
  {
    id: "vw_coding_mode",
    title: "VW/Audi: Force K-Line Init Before CAN for Legacy Modules",
    category: "Manufacturer Secret",
    makes: ["VW", "Audi", "Skoda", "SEAT"],
    difficulty: "Medium",
    description: "On VAG (VW Audi Group) vehicles with mixed CAN+K-Line architectures (2002–2008), setting your ELM327 to ATSP4 (KWP 5-baud) forces communication with legacy modules (airbags, instrument cluster, immobilizer) that don't respond on CAN.",
    steps: [
      "Connect ELM327 adapter to OBD2 port",
      "Send AT command: ATSP4",
      "Send: ATSH 81 10 F1",
      "Then send: 81 to wake up the module",
      "Module address 01=ECM, 05=Airbag, 07=Display, 11=Engine 2, 15=Airbag 2, 25=Immobilizer",
      "For immobilizer (IMMO): module 25, start byte 8C 10 F1",
    ],
    pinNote: "Uses OBD2 pin 7 (K-Line). Must use ATSP4 or ATSP5.",
    source: "builtin",
  },
  {
    id: "elm327_passthru_raw",
    title: "ELM327: Send Raw CAN Frames in Pass-Through Mode",
    category: "ELM327 Command",
    makes: ["All (CAN vehicles)"],
    difficulty: "Advanced",
    description: "The ELM327 can send arbitrary raw CAN frames when properly configured, bypassing OBD2 formatting. This is how advanced functions like UDS (Mode 27 security access, Mode 2E write) are sent to non-OBD2-standard modules.",
    steps: [
      "Set header: ATSH 7E0 (ECM) or 7B0 (BCM) etc.",
      "Disable auto-formatting: ATCAF0",
      "Send flow control: ATFCSM1 (auto FC)",
      "Set reply address: ATAR (auto receive)",
      "Now type raw hex frames: e.g. '10 03' to start a UDS diagnostic session",
      "Response will be raw hex bytes — no OBD2 interpretation",
      "UDS Service IDs: 10=session, 27=security access, 22=read by ID, 2E=write by ID, 14=clear DTC, 19=read DTC info",
    ],
    warning: "Writing to modules with raw UDS (2E service) can corrupt or brick a module. Only use with confirmed calibration files and correct module addressing.",
    source: "builtin",
  },
  {
    id: "elm327_voltage_trick",
    title: "ELM327: Read Real Battery Voltage Without Code",
    category: "ELM327 Command",
    makes: ["All"],
    difficulty: "Easy",
    description: "The ELM327 chip has a built-in voltage divider connected to the OBD2 pin 16 (battery). Sending ATRV returns the measured battery voltage directly from the hardware — no vehicle communication required.",
    steps: [
      "Connect adapter (ignition not required — runs off pin 16 battery power)",
      "Open any terminal or BLE serial app",
      "Send: ATRV",
      "Response: e.g. '12.4V'",
      "With engine off: 12.2–12.6V (healthy), below 12V (needs charging)",
      "With engine running: 13.5–14.8V (alternator charging), above 15V (overcharging)",
    ],
    source: "builtin",
  },
  {
    id: "elm327_can_monitor",
    title: "ELM327: Sniff All CAN Traffic with ATMA",
    category: "ELM327 Command",
    makes: ["All (CAN)"],
    difficulty: "Medium",
    description: "ATMA (Monitor All) puts the ELM327 into silent listen-only mode and streams every CAN frame it sees. Useful for reverse-engineering proprietary PIDs, finding BCM button codes, or diagnosing intermittent bus faults.",
    steps: [
      "Set to CAN protocol: ATSP6 (or appropriate CAN protocol for your vehicle)",
      "Disable echo: ATE0",
      "Send: ATMA",
      "ELM327 now streams all visible CAN IDs and data bytes",
      "Press any key or send CR to stop",
      "Tip: Turn a specific switch (window, HVAC, light) to identify which CAN ID carries that control signal",
      "Use ATMT XX to filter to a specific transmit ID (e.g. ATMT 130 for BCM button messages)",
    ],
    source: "builtin",
  },
  {
    id: "gm_hidden_pids",
    title: "GM: Enhanced PIDs via Mode 22 (GMLAN)",
    category: "Manufacturer Secret",
    makes: ["GM", "Chevrolet", "GMC", "Buick", "Cadillac", "Corvette"],
    difficulty: "Advanced",
    description: "GM uses UDS Mode 22 (Read Data By Identifier) for hundreds of enhanced PIDs not in the standard OBD2 set. These include individual injector pulse widths, per-cylinder AFR, transmission line pressure, battery state of health (BMS), and HVAC actuator positions.",
    steps: [
      "Set adapter header to ECM: ATSH 7E0",
      "Send a Mode 22 request: 22 F4 0C (example: engine speed)",
      "Positive response: 62 F4 0C XX XX (62 = Mode 22 response + 40)",
      "GM PID catalog (partial): F40C=RPM, F412=MAP, F401=Throttle, DDCD=Battery SoC, 4050=Trans fluid temp",
      "Use ATSH 7E2 for TCM, ATSH 7B0 for BCM",
      "Full GM PID lists available from HP Tuners or EFI Live documentation",
    ],
    source: "builtin",
  },
  {
    id: "mercedes_das_pins",
    title: "Mercedes-Benz: Pin 7+8 Sequence for DAS/SCN Coding Entry",
    category: "Manufacturer Secret",
    makes: ["Mercedes-Benz"],
    difficulty: "Advanced",
    description: "On pre-2016 Mercedes (W204, W212, W221, etc.), the diagnosis system uses pin 7 (K-Line) and the serial interface alongside CAN. Certain hidden functions (SCN coding, DAS adaptation) require the proper module addressing not exposed by generic OBD2.",
    steps: [
      "Use ATSP7 (CAN 29-bit 500kbps) for powertrain",
      "For Body/Interior modules: ATSP5 (KWP fast init) with pin 7 active",
      "Module addresses: 03=transmission, 05=SRS/Airbag, 08=AC, 19=EIS (ignition switch), 3B=TeleAid, 51=COMAND",
      "Send wakeup byte: 81 with ATSH 81 XX F1 format",
      "PIN/SCN coding requires a valid hash from Mercedes backend — no known bypass for post-2010 vehicles",
    ],
    warning: "SCN coding requires an active internet connection to Mercedes servers and a valid developer login. This cannot be bypassed without the correct server hash.",
    source: "builtin",
  },
  {
    id: "bmw_coding_enet",
    title: "BMW: Force OBD2 CAN Gateway Into Coding Mode",
    category: "Manufacturer Secret",
    makes: ["BMW", "Mini", "Rolls-Royce"],
    difficulty: "Advanced",
    description: "BMW's D-CAN protocol communicates over OBD2 pins 6+14 (CAN) using a BMW-specific UDS wrapper. Modern BMWs (F-series+) use ENET (Ethernet over OBD2 pins 1 and 9), but older E-series use D-CAN at 500kbps or 100kbps depending on the module.",
    steps: [
      "Use ATSP6 for E-series D-CAN at 500kbps",
      "Gateway (ZGW) header: ATSH 6F1 (11-bit)",
      "Send UDS session request: 10 02 (programming session)",
      "BMW uses custom DTCs in extended space (UDS DTC format, not SAE J2012)",
      "For coding: use the CAFD/FDL file format — not a raw OBD2 function",
      "E-series IBUS modules (cluster, navigation) run on separate bus accessed via Central Gateway only",
    ],
    pinNote: "E-series: CAN on pins 6+14. F-series+: ENET on pins 1+9 (100BASE-TX Ethernet).",
    source: "builtin",
  },
  {
    id: "obd2_ground_pin_trick",
    title: "Quick Ground Loop Diagnosis: Pin 4 vs Pin 5",
    category: "Pin Jump",
    makes: ["All"],
    difficulty: "Easy",
    description: "OBD2 has two grounds: pin 4 (chassis ground) and pin 5 (signal ground). On many vehicles these are tied together. If your scan tool gets intermittent communication errors, check voltage between pin 4 and pin 5 — it should be <0.1V. A higher reading indicates a ground loop or broken signal ground, causing bit errors on K-Line or CAN.",
    steps: [
      "Multimeter set to DC millivolts",
      "Probe pin 4 and pin 5 of the OBD2 connector",
      "Expected: 0–50 mV",
      ">100 mV: signal ground and chassis ground are isolated — possible broken chassis ground strap",
      "This can cause: ISO 9141 init failures, KWP timeout errors, intermittent CAN drops",
    ],
    pinNote: "Pin 4: Chassis GND, Pin 5: Signal GND. Voltage between them should be ~0V.",
    source: "builtin",
  },
  {
    id: "chrysler_drbiii_trick",
    title: "Chrysler/Jeep/Dodge: Actuate Any Output via CCD Bus Pin 3",
    category: "Manufacturer Secret",
    makes: ["Chrysler", "Dodge", "Jeep", "Ram"],
    difficulty: "Medium",
    description: "Chrysler's pre-OBD2 CCD (Chrysler Collision Detection) bus runs on pin 3 (+) and pin 11 (–) of the OBD2 connector. The PCI bus (single-wire) runs on pin 2. On 1996–2004 Chrysler vehicles, communicating over the CCD bus unlocks legacy modules (EATX, ABS) not accessible via standard OBD2.",
    steps: [
      "Use ELM327 and set: ATSP2 (J1850 VPW) as a starting point, then override to SCI",
      "Chrysler SCI (Serial Communications Interface): pin 12 TX, pin 13 RX",
      "Send break signal (300 ms low on pin 7) to wake the legacy ECU",
      "DRBIII-compatible adapters use pins 12+13 for powertrain, pins 3+11 for CCD (body modules)",
      "Most modern ELM327 clones do NOT support SCI. A CH341 or FTDI-based adapter with Chrysler-specific firmware is required",
    ],
    pinNote: "CCD Bus: Pin 3 (+) and Pin 11 (–). SCI: Pin 12 TX, Pin 13 RX.",
    source: "builtin",
  },
  {
    id: "eobd_mode_10",
    title: "EOBD / WWH-OBD: Mode $10 for Heavy Emission Testing",
    category: "ELM327 Command",
    makes: ["European", "Trucks"],
    difficulty: "Advanced",
    description: "European OBD (EOBD) and WWH-OBD (ISO 27145) use Mode $10 (UDS Diagnostic Session Control) for enhanced emission testing. This is required for Euro 6/6d-temp vehicles where Mode 01/02/03 are present but emissions data requires UDS 0x22 requests instead.",
    steps: [
      "Use ATSP6 or ATSP7 for CAN protocols",
      "Send: ATSH 7DF (functional address, all ECUs respond)",
      "Send UDS session: 10 01 (Default session) to confirm module responds",
      "EOBD emission data: UDS 0x22, DID 0xF400–0xF4FF are EOBD-specific PIDs",
      "WWH-OBD adds aggregate DTC counts and emission-relevant parameters not in standard SAE Mode 01",
    ],
    source: "builtin",
  },
  {
    id: "subaru_select_monitor",
    title: "Subaru: SSM3/SSM4 Enhanced Diagnostics via CAN + UDS",
    category: "Manufacturer Secret",
    makes: ["Subaru"],
    difficulty: "Advanced",
    description: "Subaru Select Monitor (SSM) uses a proprietary UDS extension on top of ISO 15765-4. The SSM4 protocol (2012+) communicates over CAN at 500kbps but uses Subaru-specific DID ranges for parameters not in OBD2, including individual cylinder knock values, DCCD torque split, Boxer-specific oil pressure, and EyeSight camera diagnostics.",
    steps: [
      "Set: ATSP6, ATSH 7E0",
      "Send SSM3 init: 80 10 F0 01 BF 40 (for older SSM3 on K-Line, ATSP4)",
      "SSM4 (CAN): UDS request 22 00 A8 = engine load, 22 00 20 = coolant temp (SSM DID)",
      "EyeSight module: ATSH 787, then standard UDS session and DTC reads",
      "RomRaider and OpenECU have full SSM4 DID tables for free download",
    ],
    source: "builtin",
  },
  {
    id: "elm327_fake_clone_detect",
    title: "Detect Fake ELM327 Clones — and Compensate",
    category: "ELM327 Command",
    makes: ["All"],
    difficulty: "Easy",
    description: "Counterfeit ELM327 chips (common on cheap adapters) may report firmware v1.5 but actually be v1.3 or lower. They often freeze on ATMA, don't support ATFCSD, and give wrong voltage readings. Here's how to test yours and work around limitations.",
    steps: [
      "Send ATI — genuine v2.2+ reports 'ELM327 v2.2'. If it says v1.5 but hesitates: it's likely a clone",
      "Test: send ATFCSD 30 00 00 — a real ELM327 confirms; a clone returns 'ERROR'",
      "Test: send ATST 00 — a clone may freeze instead of setting 0ms timeout",
      "Clone workaround: use ATSP6 explicitly (don't rely on ATSP0 auto-detect — clones often misidentify protocol)",
      "Clone workaround: add 200ms delay between each command in your app",
      "Clone workaround: avoid ATMA entirely — use targeted PIDs instead",
      "Genuine ELM327: OBDLink brand, BAFX Products, veepeak (STN-based) are reliable",
    ],
    source: "builtin",
  },
];

export const TRICK_CATEGORIES: TrickCategory[] = [
  "Pin Jump",
  "Diagnostic Mode",
  "ELM327 Command",
  "Manufacturer Secret",
  "Key & Immobilizer",
  "Community Tip",
];

export const TRICK_MAKES = [
  "All", "Ford", "GM", "Chevrolet", "GMC", "Chrysler", "Dodge", "Jeep", "Ram",
  "Toyota", "Lexus", "Honda", "Acura", "Nissan", "Infiniti", "Subaru", "Mazda",
  "Mitsubishi", "Hyundai", "Kia", "BMW", "Mini", "Mercedes-Benz",
  "VW", "Audi", "Porsche", "Skoda", "SEAT", "Volvo", "Land Rover", "Jaguar",
  "Alfa Romeo", "Fiat", "Peugeot", "Renault", "Citroën",
  "European", "Trucks",
];

export const CATEGORY_COLORS: Record<TrickCategory, string> = {
  "Pin Jump": "#F59E0B",
  "Diagnostic Mode": "#00D4FF",
  "ELM327 Command": "#A78BFA",
  "Manufacturer Secret": "#E879F9",
  "Key & Immobilizer": "#F472B6",
  "Community Tip": "#34D399",
};
