export interface ServiceReset {
  id: string;
  name: string;
  description: string;
  category: string;
  warning?: string;
  steps?: string[];
  requiresEngineOff?: boolean;
  requiresEngineOn?: boolean;
  icon: string;
  dangerous: boolean;
}

export const SERVICE_CATEGORIES = [
  "Engine",
  "Transmission",
  "Brakes",
  "Steering",
  "Tires",
  "Body",
  "HVAC",
  "Battery",
  "Keys & Security",
];

export const SERVICE_RESETS: ServiceReset[] = [
  {
    id: "oil_reset",
    name: "Oil Life Reset",
    description: "Reset engine oil life monitor to 100% after oil change",
    category: "Engine",
    icon: "droplet",
    dangerous: false,
    requiresEngineOff: false,
    steps: ["Turn ignition ON (engine off)", "Fully depress accelerator 3 times within 5 seconds", "Turn ignition OFF", "Start engine to verify"],
  },
  {
    id: "throttle_relearn",
    name: "Throttle Body Relearn",
    description: "Relearn throttle body idle position after cleaning or replacement",
    category: "Engine",
    icon: "activity",
    dangerous: false,
    requiresEngineOff: true,
    steps: ["Ignition ON, engine off for 60s", "Start engine", "Allow idle for 5 minutes without touching throttle", "Engine will self-calibrate"],
  },
  {
    id: "idle_relearn",
    name: "Idle Speed Relearn",
    description: "Reset idle speed adaptive values after throttle body service",
    category: "Engine",
    icon: "sliders",
    dangerous: false,
    requiresEngineOn: true,
    steps: ["Engine at operating temperature", "A/C off, all accessories off", "Allow idle for 3 minutes", "Drive cycle: idle 2 min, rev to 3000 rpm and release"],
  },
  {
    id: "evap_reset",
    name: "EVAP Monitor Reset",
    description: "Reset evaporative emission system monitor readiness",
    category: "Engine",
    icon: "cloud",
    dangerous: false,
    steps: ["Cold start required (below 86°F / 30°C)", "Complete specific OBD-II drive cycle", "Monitor will set to READY after full cycle"],
  },
  {
    id: "injector_reset",
    name: "Injector Fuel Trim Reset",
    description: "Clear long-term injector correction values and relearn",
    category: "Engine",
    icon: "zap",
    dangerous: false,
    steps: ["Clear existing adaptations", "Complete 10-minute drive cycle", "System relearns optimal fuel delivery"],
  },
  {
    id: "maf_reset",
    name: "MAF Adaptation Reset",
    description: "Reset MAF sensor adaptive values after sensor cleaning/replacement",
    category: "Engine",
    icon: "wind",
    dangerous: false,
    steps: ["Clear MAF adaptive values", "Start engine", "Perform light drive cycle for 10 minutes", "Avoid full throttle during relearn"],
  },
  {
    id: "trans_adaptive",
    name: "Trans Adaptive Reset",
    description: "Clear transmission shift adaptive data and relearn optimal shift points",
    category: "Transmission",
    icon: "git-branch",
    dangerous: true,
    warning: "Vehicle may shift poorly until relearn is complete. Drive gently for first 100 miles.",
    steps: ["Clear all adaptive data", "Drive with light throttle for first 20 miles", "Gradually increase driving intensity", "Full relearn completes at ~100 miles"],
  },
  {
    id: "tcc_reset",
    name: "TCC Adaptation Reset",
    description: "Reset torque converter clutch slip adaptation values",
    category: "Transmission",
    icon: "settings",
    dangerous: false,
    steps: ["Reset TCC slip target values", "Drive cycle at highway speeds", "System relearns at 40-80 mph"],
  },
  {
    id: "epb_retract",
    name: "EPB Retract (Service)",
    description: "Retract electric park brake pistons for rear brake pad replacement",
    category: "Brakes",
    icon: "unlock",
    dangerous: true,
    warning: "Vehicle will roll freely once EPB is retracted. Chock wheels. Do not use on a slope.",
    requiresEngineOff: true,
    steps: ["Ensure vehicle is on flat surface", "Apply wheel chocks", "Retract EPB pistons", "Replace brake pads", "Run EPB Apply procedure when complete"],
  },
  {
    id: "epb_apply",
    name: "EPB Apply (Service Complete)",
    description: "Apply/reset electric park brake after rear brake pad replacement",
    category: "Brakes",
    icon: "lock",
    dangerous: true,
    warning: "Ensure brake pads are correctly installed before running this procedure.",
    steps: ["Confirm pads installed correctly", "Apply EPB pistons to seats", "Break-in by driving 30-40 mph and applying brakes firmly 5 times"],
  },
  {
    id: "abs_bleed",
    name: "ABS Pump Bleeding",
    description: "Cycle ABS pump solenoids during brake bleeding for complete air removal",
    category: "Brakes",
    icon: "droplet",
    dangerous: true,
    warning: "Only run with brake lines open if bleeding. Do not run with system dry.",
    steps: ["Open bleed screws", "Cycle solenoids to purge ABS modulator", "Close bleed screws", "Check and top up brake fluid"],
  },
  {
    id: "brake_wear_reset",
    name: "Brake Wear Indicator Reset",
    description: "Reset brake pad wear indicator sensor after pad replacement",
    category: "Brakes",
    icon: "disc",
    dangerous: false,
    steps: ["Install new brake wear sensors", "Connect sensor connectors", "Run this reset to clear warning light"],
  },
  {
    id: "steering_angle",
    name: "Steering Angle Calibration",
    description: "Calibrate steering angle sensor after wheel alignment or component replacement",
    category: "Steering",
    icon: "navigation",
    dangerous: false,
    requiresEngineOn: true,
    steps: ["Set steering wheel to straight-ahead position", "Ensure vehicle is on flat level surface", "Run calibration procedure", "Drive slowly straight forward 10 feet to confirm"],
  },
  {
    id: "eps_reset",
    name: "EPS Torque Sensor Reset",
    description: "Reset electric power steering torque sensor calibration",
    category: "Steering",
    icon: "refresh-cw",
    dangerous: false,
    steps: ["Steering wheel at center position", "Ignition ON", "Run calibration", "Verify with test drive"],
  },
  {
    id: "tpms_relearn",
    name: "TPMS Sensor Relearn",
    description: "Register new TPMS sensor IDs after tire rotation or sensor replacement",
    category: "Tires",
    icon: "circle",
    dangerous: false,
    steps: ["Deflate and re-inflate each tire to trigger sensor", "Or drive at 50+ mph for 10 minutes", "Sensors are relearned in sequence: FL, FR, RR, RL"],
  },
  {
    id: "tpms_pressure_reset",
    name: "TPMS Pressure Baseline",
    description: "Set current tire pressures as the TPMS baseline reference",
    category: "Tires",
    icon: "trending-up",
    dangerous: false,
    steps: ["Inflate all tires to correct pressure", "Run this reset to set baseline", "Warning light should extinguish within 1 mile"],
  },
  {
    id: "window_calibration",
    name: "Window Auto-Up Calibration",
    description: "Recalibrate power window one-touch auto-up/down after battery disconnect",
    category: "Body",
    icon: "square",
    dangerous: false,
    steps: ["Lower window fully", "Raise window fully — hold button 2 seconds past fully closed", "Lower window fully — hold 2 seconds past fully open", "Raise window to test auto-up"],
  },
  {
    id: "sunroof_calibration",
    name: "Sunroof Calibration",
    description: "Recalibrate sunroof positions after battery disconnect or motor replacement",
    category: "Body",
    icon: "sun",
    dangerous: false,
    steps: ["Close sunroof fully", "Press and hold close button 10 seconds", "Sunroof will cycle to calibrate", "Release when complete"],
  },
  {
    id: "battery_registration",
    name: "Battery Registration",
    description: "Register new battery specs with BCM to maintain proper charging strategy",
    category: "Battery",
    icon: "battery-charging",
    dangerous: false,
    steps: ["Enter battery type: AGM, EFB, or Standard Lead-Acid", "Enter battery capacity (Ah)", "BCM updates charging algorithm", "Verify with voltmeter: 13.8-14.8V"],
  },
  {
    id: "alternator_reset",
    name: "Charging System Reset",
    description: "Reset alternator and charging system adaptive values",
    category: "Battery",
    icon: "zap",
    dangerous: false,
    steps: ["Clear charging system adaptive data", "Run engine for 20 minutes", "System relearns optimal charging voltage"],
  },
  {
    id: "hvac_blend",
    name: "HVAC Blend Door Calibration",
    description: "Calibrate HVAC blend door actuator positions",
    category: "HVAC",
    icon: "thermometer",
    dangerous: false,
    requiresEngineOn: false,
    steps: ["Turn off HVAC", "Run calibration — system will cycle all doors", "Process takes approximately 60 seconds", "Turn HVAC on and verify all zones work"],
  },
  {
    id: "ac_service",
    name: "A/C Service Reset",
    description: "Reset A/C service interval counter after refrigerant service",
    category: "HVAC",
    icon: "wind",
    dangerous: false,
    steps: ["Confirm A/C service completed", "Run reset to clear service warning", "Refill date is stored in BCM"],
  },
  {
    id: "key_fob_add",
    name: "Add Key Fob / Remote",
    description: "Program an additional RF key fob or smart entry remote to the BCM",
    category: "Keys & Security",
    icon: "radio",
    dangerous: false,
    requiresEngineOff: true,
    steps: [
      "Obtain a compatible blank fob or aftermarket remote for your vehicle",
      "Ensure all existing remotes you want to keep are present — some vehicles erase all during pairing",
      "Turn ignition ON (engine off)",
      "Module enters learn mode — press any button on the new fob within 30 seconds",
      "BCM will confirm reception with horn chirp or dash indicator",
      "Repeat for up to the vehicle's maximum (typically 4–8 fobs)",
      "Cycle ignition OFF to exit programming mode",
      "Test all buttons: Lock, Unlock, Trunk, Panic",
    ],
  },
  {
    id: "key_fob_relearn_all",
    name: "Relearn All Remotes",
    description: "Erase all stored fob IDs and relearn from scratch — use after replacing BCM or losing all remotes",
    category: "Keys & Security",
    icon: "refresh-cw",
    dangerous: true,
    warning: "This erases ALL currently programmed remotes. Have every fob you want to keep on hand before proceeding. You cannot undo this without reprogramming.",
    requiresEngineOff: true,
    steps: [
      "Gather all key fobs you want to keep",
      "Have a working mechanical key available to enter the vehicle afterward if needed",
      "Erase all stored remote IDs from BCM",
      "BCM enters full learn mode",
      "Press a button on each fob within 60 seconds — BCM confirms each with a chirp",
      "Cycle ignition to end session",
      "Test every programmed fob",
    ],
  },
  {
    id: "transponder_key_add",
    name: "Add Transponder / Chip Key",
    description: "Program a new IMMO transponder key to the immobilizer module so the engine will start",
    category: "Keys & Security",
    icon: "key",
    dangerous: false,
    requiresEngineOff: true,
    steps: [
      "Obtain a compatible blank key with correct chip (ID46, PCF7936, etc.) — must match your immobilizer generation",
      "Have a locksmith cut the key blade to your VIN or door lock",
      "Insert a currently working key and cycle ignition ON→OFF three times rapidly",
      "Immobilizer enters learn mode (security light flashes)",
      "Insert new key and turn ignition ON — hold for 10 seconds",
      "Security light changes pattern to confirm chip accepted",
      "Remove and test: engine should crank and start",
      "Repeat for additional spare keys up to module maximum",
    ],
  },
  {
    id: "immo_relearn_bcm",
    name: "IMMO Relearn After BCM Swap",
    description: "Re-synchronize the immobilizer and ECM after replacing the BCM or ECM",
    category: "Keys & Security",
    icon: "cpu",
    dangerous: true,
    warning: "Replacing and reprogramming an immobilizer/ECM may require the vehicle's PIN code or security access. Without the correct seed/key response the module will not accept new keys. Have the factory PIN from the original BCM or dealer records.",
    steps: [
      "Note: new BCM must be flashed with the VIN before this step",
      "Enter security access mode (requires vehicle PIN — typically 5-digit code from original BCM sticker or dealer)",
      "Module grants security access after seed/key exchange",
      "Initiate immobilizer adaptation — module syncs with ECM and transponder",
      "Insert each physical key and trigger IMMO learn sequence",
      "Verify: security light extinguishes when correct key is inserted",
      "Perform a test start cycle to confirm engine authorization",
    ],
  },
  {
    id: "all_keys_lost",
    name: "All Keys Lost Recovery",
    description: "Emergency IMMO reset when all transponder keys are lost — requires security PIN and original VIN records",
    category: "Keys & Security",
    icon: "unlock",
    dangerous: true,
    warning: "This procedure grants full engine start access to newly programmed keys. It requires the vehicle's factory PIN code. Misuse is a legal and security risk. Confirm you are the registered owner.",
    steps: [
      "Obtain the vehicle's immobilizer PIN — from original BCM sticker, dealer records, or EEPROM read",
      "Enter immobilizer security access using PIN (this module will prompt for the seed/key response)",
      "Module enters all-keys-lost mode and erases the transponder table",
      "Program at least one new blank transponder key (see 'Add Transponder Key' procedure)",
      "Re-enter security access to close the session",
      "Test start: security light must extinguish; engine must crank",
      "Program spare keys immediately — do not drive without at least two working keys",
    ],
  },
  {
    id: "remote_start_relearn",
    name: "Remote Start Module Relearn",
    description: "Re-pair an aftermarket or OEM remote start module after key or BCM changes",
    category: "Keys & Security",
    icon: "play-circle",
    dangerous: false,
    steps: [
      "Confirm remote start module is wired and powered",
      "Enter remote start module programming mode per manufacturer (usually hold dedicated button 5s)",
      "Use working programmed fob: press Lock 3× — module confirms with LED/siren",
      "Perform a 15-minute drive cycle to allow all IMMO handshakes to complete",
      "Test remote start from full distance",
    ],
  },
  {
    id: "fob_signal_test",
    name: "Key Fob Button Test",
    description: "Verify each fob button transmits a valid RF signal to the BCM receiver",
    category: "Keys & Security",
    icon: "wifi",
    dangerous: false,
    steps: [
      "Enter BCM test mode via this procedure",
      "Press each fob button — BCM logs signal strength and button ID",
      "Results show: LOCK, UNLOCK, TRUNK, PANIC signal strength (dBm)",
      "A reading below –90 dBm indicates weak battery or damaged fob",
      "Replace CR2032 / CR2025 coin cell if signal is weak",
      "Re-test after battery replacement",
    ],
  },
  {
    id: "passive_entry_calibrate",
    name: "Passive Entry Antenna Calibration",
    description: "Calibrate the low-frequency antenna zones for keyless entry and push-button start detection range",
    category: "Keys & Security",
    icon: "crosshair",
    dangerous: false,
    steps: [
      "Ensure all door/trunk LF antennas are connected",
      "Run calibration sweep — module broadcasts to each antenna in sequence",
      "Walk around the vehicle with a programmed fob — system maps the detection bubble",
      "Adjust antenna gain if detection zone is too small or bleeds into adjacent zones",
      "Confirm push-button start activates only with fob inside cabin",
    ],
  },
];
